### ISSUE TITLE
Frequency map may choose wrong frequency based on hint

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1009]
The algorithm for the frequency map agent sample the region hint value the first time a region is encountered.  The hint may change throughout the region exection, but these changes would not effect the frequency selected by these agents which is fixed based on the first time sample.  If a compute bound region were to begin with a brief call to MPI, the frequency would be set to the minimum for the entire execution of the region.

**Comment by bgeltz** [comment]
> If a compute bound region were to begin with a brief call to MPI, the frequency would be set to the minimum for the entire execution of the region.

I'm not sure how to resolve this bit here about the *minimum* being used for the whole region with this other blurb in #1051 about the *maximum*:
>Write an integration test that calls MPI within a user defined region that has a compute hint directly after region entry.
Inspect the report and show that the region is assigned the maximum frequency when running the frequency map agent

The FrequencyMapAgent sets compute regions to max frequency.  Is that what you meant @cmcantalupo ?
