### ISSUE TITLE
Unable to run geopmbench with impi on system D

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#1045]
This is with geopm 1.1.0.

```
$ OMP_NUM_THREADS=1 geopmlaunch impi -n 1 -ppn 1 --geopm-hyperthreads-disable --geopm-preload -- geopmbench ~/bench.conf
Warning: <geopm> geopmpy.launcher: Hosts not defined, GEOPM may fail to start.  Use "-f <host_file>" or "-hosts" to specify the hostnames of the compute nodes.
mpiexec.hydra -ppn 1 -n 1 -bootstrap slurm geopmread --cache
OMP_PROC_BIND=true GEOPM_CTL=process GEOPM_PROFILE= GEOPM_REPORT=geopm.report KMP_AFFINITY=disabled MV2_ENABLE_AFFINITY=0 KMP_WARNINGS=FALSE I_MPI_PIN_DOMAIN=[2,800000000] LD_PRELOAD=libgeopm.so mpiexec.hydra -ppn 2 -n 2 -bootstrap slurm geopmbench systemDhome/dwilson/bench.conf
Error: <geopm> Runtime error: ControlMessageImp::wait(): systemD: is_ctl=1 : is_writer=1 : Timed out waiting for status 1: at geopm/src/ControlMessage.cpp:108
Warning: <geopm> Controller handshake failed, running without geopm.
<geopm> No such file or directory
Beginning loop of 1 iterations.
Completed loop.
<geopmpy.launcher> Command 'mpiexec.hydra -ppn 2 -n 2 -bootstrap slurm geopmbench systemDhome/bench.conf' returned non-zero exit status 255.
```

`strace` indicates that the generic EEXIST error came from trying to open the shared memory.

Before reaching the above example, I was also seeing failures without `--geopm-preload`. Srun of the benchmark works fine on this system.

This attempt was built with `./configure --prefix=$HOME/build/geopm_intel_impi CC=$(which mpicc) CXX=$(which mpicxx) FC=$(which mpifc) F77=$(which mpif77) CFLAGS="-xCORE-AVX2" CXXFLAGS="-xCORE-AVX2" FCFLAGS="-xCORE-AVX2" FFLAGS="-xCORE-AVX2 -fnofor_main" --enable-debug LDFLAGS="-dynamic"`, with `mkl` loaded and `compilervars.sh intel64` run first. 

My earlier attempts also failed with `./configure --prefix='...'` also failed.

**Comment by bgeltz** [comment]
Won't fix; not an issue on dev.
