### ISSUE TITLE
Remove deprecated methods and classes from MSR interface

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#1055]
> estimate 1

Several MSR-related headers are installed, including MSR.hpp, MSRIO.hpp, MSRSignal.hpp, MSRControl.hpp and MSRIOGroup.hpp.  Any deprecated interfaces or classes should be removed with the 2.0 release.

**Comment by cmcantalupo** [comment]
https://github.com/geopm/geopm/commit/6c9c333fa9da59a6631772eb26da69478dff5bde
