### ISSUE TITLE
Add descriptions for aliases and commonly used signals in MSRIOGroup

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#1061]
> estimate 1

Many signals are missing descriptions other than "Refer to the SDM".  These should have some more understandable description, which is used when listing signals with geopmread.  Showing units for each signal can be implemented separately with #487.

Done Criteria:
1. Get guidance regarding documentation

**Comment by bgeltz** [comment]
Current status:
http://mcfly.ra.intel.com/~bgeltz/desc/signals.txt
http://mcfly.ra.intel.com/~bgeltz/desc/controls.txt
