### ISSUE TITLE
Add control loop period as parameter to all agents that wait() on time

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1065]
Could also be specified as a rate.

**Comment by dianarg** [comment]
Might be duplicate #576

**Comment by cmcantalupo** [comment]
We need to get rid of the `void Agent::wait(void)` method and replace it with an `double Agent::wait_time(void)` method that specifies the default control interval time target.

**Comment by cmcantalupo** [comment]
Be nice to also have a command line override for the wait_time().  In the mean time a simple solution 

```
void MonitorAgent::wait(void)
{
    double timeout = m_policy[M_POLICY_WAIT_TIME]; // Could come from Environment class in the future
    Agent::wait(timeout);
}
```

With Agent::wait() as a static method of the base class.

**Comment by bgeltz** [comment]
Related to #1411
