### ISSUE TITLE
REGION_HASH signal does not indicate whether a CPU is actually in use by the app

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#1070]
REGION_HASH is reported to be unmarked for a cpu if a) the application is running there in an unmarked region; or b) if no application ranks are running there.

**Comment by cmcantalupo** [comment]
This is resolved not by the region hash, but with the GEOPM_REGION_HINT_INACTIVE hint.  The user can get the ApplicationSampler::per_cpu_hint() to resolve if a core is in active use by the tracked application.
