### ISSUE TITLE
Determine best procedure for determining uncore freq limits

### ISSUE THREAD

**Issue by sidjana** [geopm/geopm#1079]
> estimate 1

Related to #1075 

Done Criteria:
---------------
1.  reach out to the research team 

Potential workaround for future work:
------------------------------------------
Min and max for each arch isn't published, but I believe it could be determined by asking for max = min = 0, checking uncore status.  then max = min = 0xff and checking uncore status

**Comment by bgeltz** [comment]
Current sketch of this procedure is here:
https://gist.github.com/bgeltz/9f2d143090f98ca7ea6be041d933c0d2

**Comment by bgeltz** [comment]
This looks to be the only way to reliably get at these bounds.  The next steps here will be to integrate that sketch into the runtime somewhere.  It makes sense that this should be the responsibility of the MSRIOGroup, but we probably don't want to perform this probing as a part of Controller startup if we can help it.

Chris's idea is to add it to the call path from geopmread that does the lscpu caching.  We'll have to figure this out as a part of the implementation task.
