### ISSUE TITLE
EE Agent can violate PERF_MARGIN

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#1096]
The energy_efficient agent's region runtime can exceed the limit specified by PERF_MARGIN. The first section of this report outlines how to reproduce the issue. The second part discusses the suspected root-cause and a potential solution.

**Simplified reproducer on the team's cluster**:
The performance numbers come from release v1.1.0, but this behavior is also reproducible on the latest dev (649a766).

```
$ cat bench.conf
{"loop-count": 100, "region": ["dgemm"], "big-o": [5]}
$ cat ee.json
{"FREQ_MIN": 1000000000, "FREQ_MAX": 2100000000, "PERF_MARGIN": 0.1}
$ cat fma.json
{ "FREQ_MIN": 2100000000, "FREQ_MAX": 2100000000 }
$ OMP_NUM_THREADS=1 geopmlaunch srun -N1 -n42 --geopm-agent frequency_map --geopm-policy fma.json --geopm-report fma.report -- geopmbench ./bench.conf
$ OMP_NUM_THREADS=1 geopmlaunch srun -N1 -n42 --geopm-agent energy_efficient --geopm-policy ee.json --geopm-report ee.report -- geopmbench ./bench.conf
```
The resulting time differences are:
```
$ grep -A1 dgemm {fma,ee}.report
fma.report:Region dgemm (0x00000000a74bbf35):
fma.report-    runtime (sec): 80.7125
--
ee.report:Region dgemm (0x00000000a74bbf35):
ee.report-    runtime (sec): 89.7812
```

PERF_MARGIN was set to 10%, but the EE agent resulted in an 11.2% runtime increase.

Note that this effect doesn't diminish with greater iteration counts. I only did the lower iteration count since it takes a shorter time to reproduce. The same experiment with a 500 iteration run results in 12.8% time increase:
```
$ grep -A1 dgemm {fma,ee}.report
fma.report:Region dgemm (0x00000000a74bbf35):
fma.report-    runtime (sec): 404.314
--
ee.report:Region dgemm (0x00000000a74bbf35):
ee.report-    runtime (sec): 456.25
```

The same experiment on dev results in similar output (though I had to use a different bench.conf to get similarly-sized dgemm regions in head of dev):
```
$ cat bench.conf
{"loop-count": 100, "region": ["dgemm"], "big-o": [0.02]}
$ grep -A1 -w dgemm {fma,ee}_dev.report
fma_dev.report:Region dgemm (0x00000000a74bbf35):
fma_dev.report-    runtime (sec): 89.9096
--
ee_dev.report:Region dgemm (0x00000000a74bbf35):
ee_dev.report-    runtime (sec): 100.653
```

**Suspected Cause**:
This may be due to the filtering mechanism in EnergyEfficientRegion.cpp (snippet below). Perf (negative runtime) is tracked over a 5-region window. The windowed max is used to determine both the reference performance and the target performance. Max is conservatively used on the reference performance so that 10% degradation is with respect to the best case. However, the use of max on the target window biases toward lower frequencies in noisy performance scenarios.

With 100 MHz steps at a 2.1 GHz starting point, this means some cases can effectively have up to an extra 0.0476 unintended PERF_MARGIN impact.

Relevant code, from EnergyEfficientRegion.cpp:
```
                double perf_max = Agg::max(curr_perf_buffer->make_vector());
                if (!std::isnan(perf_max) && perf_max != 0.0) {
                    if (m_target == 0.0) {
                        m_target = (1.0 + m_perf_margin) * perf_max;
                    }
                    bool do_increase = false;
                    if (m_target != 0.0) {
                        // Performance is in range; lower frequency
                        if (perf_max > m_target) {

```

Using a median filter in place of the final if statement seems to resolve this. However, I'm not sure if another technique would be more appropriate. 7.1% in this case:
```
$ grep -A1 dgemm ee_modified.report
Region dgemm (0x00000000a74bbf35):
    runtime (sec): 86.4101
```

**Comment by bgeltz** [comment]
Will not fix; agent no longer exists primarily because of this issue.
