### ISSUE TITLE
As a user I'd like to enable IOCTL write for controls that are not 64 bits wide

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1112]
> estimate 5

If the --enable-msr-safe-ioctl-write configure option is provided and any of the controls that are modified by an agent are not full width MSR's and error will occur (zeros will be written outside of the control bits).

The uncore frequency and the RAPL controls are effected and even the IA32_PERF_CTL register has bits that are marked as "reserved".

Done criterion:
- Add MSRIO::add_write() and MSRIO::adjust() methods.
- MSRIO is responsible for combining multiple adjusts to the same register.
- Add new Control abstract base class and MSRFieldControl derived class to support bit -> SI unit conversion to call add_write() and adjust() methods.
- Update MSRIOGroup to use new MSRIO features.
- Clear out unused methods from MSRIO class.

**Comment by dianarg** [comment]
Completed with #1115
