### ISSUE TITLE
The geopm_tprof_init_loop() does not calculate denominator properly

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1130]
The "unchunked" counter is the total number of unchunked work units, but it is being used as if it is the number of unchunked units per unfull thread:  it should roughly be divided by (num_thread - last_full_thread).  

https://github.com/geopm/geopm/blob/dev/src/ProfileThreadTable.cpp#L82

**Comment by dianarg** [comment]
This API will be deprecated in favor of `geopm_tprof_init()` only.
