### ISSUE TITLE
Trace progress for user defined regions contains false entries/exits.

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#114]
If a region makes a call into MPI the trace output erroneously contains entries/exits (progress toggle form 0 to 1) associated with the implicit nested MPI region .

**Comment by cmcantalupo** [comment]
Started a branch to try to fix this issue here:

https://github.com/cmcantalupo/geopm/tree/cmcantalupo-fix-trace-mpi-false-progress

the patch is not yet tested.

**Comment by bgeltz** [comment]
This has probably been fixed with the Agent code path, but needs validated prior to closing.
