### ISSUE TITLE
linking with json

### ISSUE THREAD

**Issue by bkmgit** [geopm/geopm#115]
When building with current version of libjson (0.9 from https://s3.amazonaws.com/json-c_releases/releases/index.html or with latest code at https://github.com/json-c/json-c), linking fails since library names have changed from json-c to json. For release 0.12, current linking works.

**Comment by cmcantalupo** [comment]
Thanks for the feedback!  I'll modify the configure script accordingly.

**Comment by dianarg** [comment]
We have changed the code to use a different JSON library, which is now distributed with GEOPM in the contrib directory.  There should no longer be any dependency on json-c.  Let me know if you still notice any linking problems.
