### ISSUE TITLE
Intermittent failures of test_frequency_sane_fmap integration test

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1155]
There is a race condition where if the controller's first sample of the region is prior to the hint change due to the entry into a network sub-region then the report includes the map for the region otherwise it does not.  For this reason the failure of the integration test is intermittent.

Proposed solution: 
1. Make the agent aware of the MPI regions that we care about in the runtime.  The agent should not care about the hint any longer.

2. If we are not in a user marked region and we encounter an MPI region, do what the agent(s) normally does with the MPI regions.

**Comment by bgeltz** [comment]
Grep for the MPI funcs we care about:
```$ grep -B 3 GEOPM_PMPI_ENTER_MACRO geopm_pmpi.c | grep "int MPI" | cut -d\( -f1 | cut -d' ' -f2```

With that list, you should be able to call the string to region hash function to get the map you need.
