### ISSUE TITLE
Figure out long term solution for filter documentation and flesh out the documentation for the edit distance filter

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1177]
> estimate 1

Currently all of the documentation for the proxy region epoch filter is in the launcher man page.  Probably makes sense to separate that out into a separate page, and add a new page for each filter. 

Done criteria:
- New pages added for each filter.
- More detailed description of how to use the edit distance filter.

parent story: #1173

**Comment by dianarg** [comment]
Probably will get moved to future sprint

**Comment by dianarg** [comment]
Chris likes what we have currently.  No need to create a separate man page for this topic.
