### ISSUE TITLE
Manually run miniFE, nasFFT, nekbone, and gadget with existing script, but using edit distance filter

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1178]
> estimate 1

Modify existing scripts used to generate test profile trace data to actually run with the edit distance filter.  Remove all geopm modifications from benchmarks.  Run with the monitor.

Done criteria:
- The runtime doesn't fail, or an issue is filed for each failure.
- Examine profile trace and EPOCH_COUNT events

Parent story: #1180

**Comment by fkeceli** [comment]
Few questions/comments:

- Is this referring to adding all these apps to GEOPM as an integration test or is it just a step towards it?
- Note that GADGET is not fully detected by APD unless we do some manual trace filtering which is not implemented in GEOPM.
- Ali is working on adding HACC to this.

**Comment by dianarg** [comment]
Nekbone, minife, and FFT can run successfully.  Issue opened for gadget: #1188
