### ISSUE TITLE
As a user of the power balancer agent, I would like balance power between sockets on a dual socket Xeon system

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1191]
The current implementation in dev balances power between compute nodes, but always splits the power budget evenly between sockets on a single node.  The implementation must be modified to support treating each RAPL domain as an independent domain.

**Comment by bgeltz** [comment]
The updated power_balancer agent is now available here:
https://github.com/geopm/geopm/tree/power-balancer

It has not yet been merged to dev because of broken unit tests.
