### ISSUE TITLE
As a user of GEOPM on system D I would like run and analyze nekbone and gadget with different agents

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1197]
> estimate 3

Done criteria:
- Determine good input parameters / problem sizes to run on 128 - 256 nodes for both apps.
- Measure power consumption and check that we are somewhat near TDP.
- Profile name should include the application name and the iteration number.
- Share results with the rest of the team to make sure we are on target.
- Run power sweep with balancer and governor after good results are obtained with the monitor.

**Comment by bgeltz** [comment]
On the last bullet now.  Jobs are queued.
