### ISSUE TITLE
As a user of the integration infrastructure, I would like to easily run frequency sweep experiments

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#1222]
> estimate ?

Continuation of work started in #1209.  The goal of this story is to be able to produce the same frequency-sweep-based analysis output from geopmanalysis

Done criteria
--------------
- [x] Example frequency sweep run script with DGEMM
- [x] Script to print per-region summary of data from frequency sweep
- [x] Script to produce a region frequency map given a frequency sweep and a performance margin
- [x] Script to produce plots of runtime and energy vs. fixed frequency (generate_runtime_energy_plot())

**Comment by bgeltz** [comment]
I just pushed a new commit to the branch for this on my fork:
https://github.com/bgeltz/geopm/tree/dianarg-freq-sweep
https://github.com/bgeltz/geopm/commit/fd39b61b6d334e252c9d1a0c2bab5b0c7f3ed860

This should address the second bullet in the Done Criteria.

Example output:
http://mcfly.ra.intel.com/~bgeltz/brg_manual/region_stats.log
http://mcfly.ra.intel.com/~bgeltz/brg_manual/region_mean_stats.log
