### ISSUE TITLE
Add GADGET to the integration infrastructure

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1245]
> estimate 5

Parent story: #1278

Parent story describes done criteria and process for this task which is specific to GADGET.

see https://github.com/bgeltz/geopm/blob/task-1081/test_integration/test_gadget.py

**Comment by bgeltz** [comment]
Updated this to a 5 (was a 3).  With the FFTW, GSL, etc. dependencies, doing this "right" is going to take a lot of scripting.
