### ISSUE TITLE
Ignore short running regions

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#125]
Modify the frequency decider to only modify frequency if the runtime is long enough that the latency of control allows for the switch to occur in time.

**Comment by dianarg** [comment]
Proposing that we try to include this is 1.0.  Running the EnergyEfficientAgent with nekbone from our examples unmodified appears to only degrade performance without saving energy because of its short regions.

**Comment by dianarg** [comment]
@sbtrasi
