### ISSUE TITLE
Modify build of nekbone to enable the generation of a special binary with MPI_Barriers added to it to support #1242

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1253]
> estimate 3

Parent story: #1242

Done criteria:
- Dev branch has patches committed and build script modified to support this build of nekbone
- Updates to the NekboneAppConf constructor that support selection of the path to the new binary.

**Comment by bgeltz** [comment]
Use the monitor data to identify which MPI regions are running log enough that inserting a Barrier is a viable strategy.
