### ISSUE TITLE
Execute run scripts from #1254 and inspect results

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1255]
> estimate 3

If there is any useful scripting done to better understand the data, feed this back into the integration directory scripts. This task may also require rerunning the experiment with modifications to get better results (lower noise, deal with thermals, whatever).

Parent story: #1242 
Check on thermal status and temperature drifts over the run.

Done criteria:
- Generate enough data so that an analysis can be performed.
- The noise is well understood, and a clear conclusion is drawn from the data

**Comment by dianarg** [comment]
Also check uncore status register
