### ISSUE TITLE
Use PlatformIO in place of Platform in Controller

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#127]
Much of the functionality of the Platform is now supported by the PlatformIO class.  Change the Controller to use PlatformIO for all currently working features of PlatformIO.

**Comment by cmcantalupo** [comment]
Related to issue https://github.com/geopm/geopm/issues/128 and both need to be broken down more cleanly into digestible tasks.

**Comment by dianarg** [comment]
Closing to prioritize #227
