### ISSUE TITLE
Add support for more platforms in PlatformIO

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#129]
The MSR array defined at the bottom of PlatformIO.cpp is only filled out for the KNL platform.  Add support for other architectures like BDX and HSX.

**Comment by cmcantalupo** [comment]
@slabasan I think you mentioned that you had done this for some platforms other than KNL.  If so can you share the code?  Thanks!

**Comment by slabasan** [comment]
I started to populate the SNB MSR list on the `slabasan-populate-snb-msrs` branch here: [https://github.com/slabasan/geopm/tree/slabasan-populate-snb-msrs].

**Comment by slabasan** [comment]
@cmcantalupo I had some updates to my `slabasan-populate-snb-msrs` branch, but I am not sure how to update the existing change on Gerrit. Is it as simple as doing a `git push gerrit slabasan-populate-snb-msrs`, where `gerrit` is `https://review.gerrithub.io/geopm/geopm`?

**Comment by dianarg** [comment]
SNB, BDX/HSX are supported in PlatformIO.  Support for SKX has also been added.  Updates from @slabasan regarding the PERF_STATUS domain for Haswell were incorporated at one point (later changed from CPU to CORE).  Thanks Stephanie!

https://review.gerrithub.io/c/geopm/geopm/+/391682
https://review.gerrithub.io/c/geopm/geopm/+/398837
https://review.gerrithub.io/c/geopm/geopm/+/411487
