### ISSUE TITLE
Port FFT infrastruture to large scale system

### ISSUE THREAD

**Issue by sidjana** [geopm/geopm#1301]
> estimate 2

Parent story #1279

**Comment by cmcantalupo** [comment]
WIP here:

https://github.com/cmcantalupo/geopm/tree/apps-fftw

**Comment by cmcantalupo** [comment]
Gross patch that enables the run at large scale is posted here:

https://github.com/geopm/geopm/pull/1317

We should just remove FFT from the autotools build and use the original NAS source code.
