### ISSUE TITLE
geopmpy.launcher improperly selects OMP num thread count

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#131]
geopmpy.launcher selects more OMP threads than can be used when application ranks are isolated to their own physical cores (with hyper threading enabled).

**Comment by cmcantalupo** [comment]
At the very least we should warn if OMP_NUM_THREADS is not set by the user.

**Comment by cmcantalupo** [comment]
https://github.com/geopm/geopm/commit/ca374e0a3ccbfb70351524af10db65e1da6878de
