### ISSUE TITLE
Deprecate default implementation of Agent::enforce_policy

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#1333]
> estimate 1

**Comment by cmcantalupo** [comment]
Simply make this method pure virtual:

https://github.com/geopm/geopm/blob/dev/src/Agent.hpp#L132

**Comment by bgeltz** [comment]
Updated link:
https://github.com/geopm/geopm/blob/50d1721ba0f6d9b60bbcc822232715dc51695c4c/src/Agent.hpp#L105
