### ISSUE TITLE
Remove PlatformIO dependency on hwloc

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#145]
PlatformTopology currently uses hwloc but it can parse the output of lscpu instead.

**Comment by cmcantalupo** [comment]
Implementation for PlatformTopo will replace PlatformTopology and will be based on lscpu not libhwloc.

**Comment by cmcantalupo** [comment]
https://review.gerrithub.io/#/c/396258/
https://review.gerrithub.io/#/c/396259/
