### ISSUE TITLE
Report file time reporting curiosities (lists time-hint-unset for no reason, sum is not equal to sync-runtime)

### ISSUE THREAD

**Issue by fkeceli** [geopm/geopm#1472]
Ran with public new-profile branch

Observation:
```
Hosts:
  mcfly1:
    regions:
    -
      name: section1
      hash: 0xb52215e3
      runtime (s): 2211.32
      count: 59217
      sync-runtime (s): 2143.04
      ...
      time-hint-network (s): 19.4342
      time-hint-ignore (s): 0
      time-hint-compute (s): 0
      time-hint-memory (s): 0
      time-hint-io (s): 0
      time-hint-serial (s): 0
      time-hint-parallel (s): 0
      time-hint-unknown (s): 1002.42
      time-hint-unset (s): 1119.55
```

There are two curiosities here:

1. time-hint-unset is non-zero, which is unexpected since the regions is marked with "unknown" hint and there are only MPI and OMP sections down in its hierarch (no user defined nested regions).
2. The sum of the time-hint-* fields is very close but not exactly equal to the sync-runtime (2141.4042 vs 2143.04). I would expect them to be the same.

Above numbers are obtained from a pennant run via the integration infrastructure. Command:

```
python3 ${GEOPM_SOURCE}/integration/experiment/monitor/run_monitor_pennant.py \
    --pennant-cores-per-node=${num_cores} \
    --pennant-cores-per-rank=${OMP_NUM_THREADS} \
    --pennant-input=${data_file} \
    --output-dir=${OUTPUT_DIR} \
    --enable-traces \
    --node-count=${SLURM_NNODES} \
    ${GEOPM_INTEGRATION_OPTIONS} \
    ${GEOPM_SIGNAL_OPTIONS}
```
 The parameters for the run is as follows:

```
num_cores: 42
OMP_NUM_THREADS: 1
data_file: PENNANT/test/leblancx16/leblancx16.pnt
Sbatch is called with: -N 16
```
Runtime for this run should be ~1hr.

A shorter run should exhibit the same curiosities:
```
num_cores: 42
OMP_NUM_THREADS: 1
data_file: PENNANT/test/leblancx4/leblancx4.pnt
Sbatch is called with: -N 8
```
This run should take about 100 secs. 8 can be increased to 12 or 16 for shorter runtime.

**Comment by cmcantalupo** [comment]
Issue only exists on the new-profile branch and it was fixed with https://github.com/geopm/geopm/issues/1502
