### ISSUE TITLE
Create class for supporting geopmpolicy CLI

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#151]
Currently the Platform class has methods that should be delegated to a special class used by the geopmpolicy command line tool.  These interfaces will be wrappers around the appropriate PlatformIO method calls.

**Comment by dianarg** [comment]
Obsolete now that Controller/PlatformImp control path will be replaced: #381 
Creating configurations is supported by the geopmagent binary.
Save/restore MSRs is available through msrsave from the msr-safe project. 
Enforcing policy without the runtime is available using geopmwrite.
The remaining functionality around whitelists will be implemented with #255
