### ISSUE TITLE
Invalid report when application has no regions

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#1517]
When an application has no regions (user marked, MPI, or otherwise) the `Regions:` section of the report contains nothing.  It should be an empty list, e.g. `Regions: [] `.  The report parsing and caching in io.py also needs to be updated to support an empty regions dataframe.

A workaround is to add at least one MPI call to any application with no regions.

See #1513

**Comment by cmcantalupo** [comment]
Related to
https://github.com/geopm/geopm/issues/1570
?

**Comment by bgeltz** [comment]
This was done already:
https://github.com/geopm/geopm/issues/1570#issuecomment-1081137292

Thought we still need to update io.py:
```
======================================================================
ERROR: test_count (__main__.TestIntegration_monitor)
Test that region and epoch counts in the report match expected
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_monitor.py", line 106, in test_count
    spin_data = self._report.raw_region(node, 'spin')
  File "/home/bgeltz/build/geopm/lib/python3.6/site-packages/geopmpy/io.py", line 785, in raw_region
    for rr in self._raw_dict['Hosts'][host_name]['Regions']:
KeyError: 'Regions'
```
