### ISSUE TITLE
lscpu cache persists on reboot

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#1548]
On systems where the contents of /tmp persist between reboots (which is most systems by default), the lscpu cache may be incorrect because of e.g. BIOS changes.

A solution should be developed to ensure that the cache is correct.  Presently we've discussed 2 possibilities:
1. ~~Remove the cache at the end of a run, always.~~
2. Compare the cache file's last modified time against the system uptime, and if the uptime is newer remove the old file.

https://man7.org/linux/man-pages/man2/sysinfo.2.html

**Comment by cmcantalupo** [comment]
Something strange is going on in the test constructor (repeats the calls in both constructors):

https://github.com/geopm/geopm/commit/b5697434dafff8fa3a91f0a479895cec06a5d12f

Not sure what this is about.
