### ISSUE TITLE
Enable better unit test coverage of the SSTIO class

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1573]
Currently the SSTIO class is the last level abstraction for the SST driver interface.  This class has a non-trivial amount of logic that is not covered by unit tests.  Perhaps a better last level abstraction would be a class that implements only the call to ioctl(2), perhaps named SSTIoctl.  This class would be a functor (implement the () operator) and take as inputs pointers to the structures that are required for the SSTIO calls to the ioctl(2) system call (the file descriptor and request number would be stored in the SSTIoctl class).  To test the SSTIO class you could mock out this object when there are expected calls to ioctl(2).  

Note: A similar strategy could (in principle) be applied to the MSRIO class in order to get coverage of its ioctl(2) calls, however for the MSRIO class, the coverage for most of the logic comes by mocking the file descriptors for read(2) and write(2) calls.

**Comment by dannosliwcd** [comment]
Resolved by #1655
