### ISSUE TITLE
The geopmlaunch command warns that cores are oversubscribed but they are not

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1613]
There are many configurations where the following message is printed erroneously:

```Warning: <geopm> geopmpy.launcher: User requested all cores for application. GEOPM controller will share a core with the application.```

On a dual socket system this will reported unless at least *four* cores are left unused.  Especially now that we have changed the affinity pinning logic for the controller, this issue needs to be addressed.

**Comment by bgeltz** [comment]
Move this warning to the Controller where the other recent pinning changes have been made.  This warning is a red herring now that the Controller pins itself.

Additionally an issue should be opened (if it doesn't exist) about optimizing the app pinning in the launcher now that the Controller is pinning itself.
