### ISSUE TITLE
GOMP/pthread interaction broken

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#163]
Building with the GNU toolchain and attempting to use the pthread launch mechanism for the controller is currently broken.  The current workaround is to remove OMP_PROC_BIND from the launch line, but this may introduce other issues.  The current error is:

    Error: Invalid argument: Controller::pthread(): pthread_create() failed: at geopm/src/Controller.cpp:515
    Invalid argumentERROR: /home/bgeltz/geopm/.libs/geopmbench: Invalid argument

**Comment by dianarg** [comment]
Is this related/duplicate of #987 ?

**Comment by dianarg** [comment]
Fixed
