### ISSUE TITLE
As a developer of the GEOPM service I would like to ensure that all user input is properly vetted

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1676]
It is especially important to test that the service is robust in all user facing interfaces to bad or malicious input. 

We know that better error checking is required of the GEOPM_PROFILE environment variable.  This task is to look for any other potential related issues and fix them.

**Comment by cmcantalupo** [comment]
Requires review of existing tests and determine if there are existing gaps.  Many if not all of our user facing interfaces have robust unit tests.

**Comment by dannosliwcd** [comment]
One known case is geopm profile names. Users can input `--geopm-profile=[0, 1, 2, anything that parses as a complex yaml data structure]` and it will bubble through to our report files which will be interpreted as yaml. In that specific case, a solution could be to write the profile (or any field) to the report in a way that ensures it is interpreted as a string, e.g., by using a full yaml-aware dumper.
