### ISSUE TITLE
geopm.spec file specifies invalid dependency on SLES15

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#1682]
https://github.com/geopm/geopm/blob/cdb2abc175dfaf3fc3d4f8eda5c4b677ed1c47af/geopm.spec.in#L44 
Calls out elfutils-libelf-devel as a dependency, which is libelf-devel in SLES15.

**Comment by dannosliwcd** [comment]
OBS builds pass with SLES15 now. It looks like this issue was resolved with #1700
