### ISSUE TITLE
Use secure C string functions

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#1778]
We should be using the "secure" variants of all the C string functions in our code.
e.g. use ```strncpy_s``` instead of ```strncpy```

More info:
https://en.cppreference.com/w/c/string/byte/strncpy
https://us-cert.cisa.gov/bsi/articles/knowledge/coding-practices/strncpy_s%28%29-and-strncat_s%28%29

**Comment by cmcantalupo** [comment]
https://stackoverflow.com/questions/40045973/strcpy-s-not-working-with-gcc
