### ISSUE TITLE
Support plugin parameters in the GEOPM configuation file.

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#179]
Add some mechanism to pass parameters to decider plugins based on the GEOPM configuration file.  Could be as simple as an entry in the GEOPM configuration json file that points to a file path that configures the parameters for a plugin.  This will enable the authority that generates the configuration file to control the behavior of the plugins.

**Comment by bakerbrandond** [comment]
Agent's are now JSON policy file driven.
