### ISSUE TITLE
Change ZES_ENABLE_SYSMAN to LOW_POWER variant

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#1800]
https://github.com/geopm/geopm/blob/a1b382812fc96d69ddadaef486a5e77485a47778/src/LevelZero.cpp#L55

Sysman now supports a ZES_ENABLE_SYSMAN_LOW_POWER variant that should be used.
https://spec.oneapi.io/level-zero/latest/sysman/PROG.html#environment-variables

**Comment by lhlawson** [comment]
Close when we close #2205 if we take the approach of requiring the user to set the ENV var themselves

**Comment by bgeltz** [comment]
Previously mentioned issue addresses this in docu.  The expectation is that the user will set this.
