### ISSUE TITLE
Update Plugin Developer's Guide to reflect new interfaces

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#181]
The guide should describe the new interfaces used to write plugins using PlatformIO and updates to how plugins work. 

Other important notes that should be mentioned in the updated guide:
- Naming conventions for plugins, signal and control names, and signal/control aliases.
- The difference between region runtime and telemetry timestamp.
- Relationship between Deciders and PlatformIO
- List of built-in high level signal/control aliases (this should also be in man pages)
- How sampling works and what determines frequency of samples

**Comment by dianarg** [comment]
For beta, documentation will be covered by new tutorials for the IOGroup and Agent.

**Comment by bgeltz** [comment]
We have tutorials for this now.  Also, the old guide has been removed.
