### ISSUE TITLE
Accelerator IOGroups (NVML & LevelZero) do not hide controls that the user does not have permission to use

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#1813]
Parent issue: #1690 

Both NVML and LevelZero provide a mechanism to determine if users have access to various controls.  These should be used to selectively remove controls from the m_control_available list if the user does not have the appropriate permissions, vs the current approach of try/catch handling of 'INSUFFICIENT PERMISSION' errors for things such as save & restore.

**Comment by cmcantalupo** [comment]
Will be resolved with #2130
