### ISSUE TITLE
Define last level abstraction for sigwait(2) and sigwaitinfo(2) sigtimedwait(2) sigaction(2) kill(2)

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1856]
> estimate 3

Parent issue: #1857 

We will need a class that abstracts the system calls around waiting for signals to occur.  It is expected that issue #1687 will require the following four calls: sigwait(2), sigwaitinfo(2), and sigtimedwait(2) and sigaction(2) kill(2).  Since this is a last level abstraction, we don't need unit tests, but the implementation should be very thin.

Done criteria:
- [x] Define POSIXSignal class header that enables the required features
- [x] Implement the class with thin wrappers around system calls
- [x] Push PR into geopm-service branch (or dev if already merged)

**Comment by cmcantalupo** [comment]
Work is started here:

https://github.com/cmcantalupo/geopm/tree/issue-1856

**Comment by Krebrov001** [comment]
Note to self:

## Unit Tests

 - Testing the `POSIXSignalImp`

- we should create unit tests for the two helper methods in *this particular pull request*
  - `reduce_info()`
  - `make_sigset()`
