### ISSUE TITLE
As a user of the python controller/agent infrastructure I would like to be able to call Controller.run() multiple times

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1862]
> estimate 1

At least one additional method for the Agent class must be defined to tell the agent object that a new run is beginning.  May also want another method that defines the end of a run for the agent.  The Agent.get_report() method could be used for this purpose, but seems to be overloading the interface.

**Comment by fkeceli** [comment]
Along the same lines of thought I believe argv (argument for application) should be moved from Controller constructor to the run method.
