### ISSUE TITLE
FREQUENCY_ACCELERATOR_CONTROL should be renamed

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#1870]
ACCELERATOR_FREQUENCY_CONTROL following the pattern of CPU_FREQUENCY_CONTROL

**Comment by lhlawson** [comment]
Currently GPUCHIP_FREQUENCY_CONTROl for LevelZero and GPU_FREQUENCY_CONTROL for NVML.

**Comment by bgeltz** [comment]
Closed with #2425
