### ISSUE TITLE
Spack and geopm

### ISSUE THREAD

**Issue by maiterth** [geopm/geopm#1874]
I got a ping on geopm usage with spack on a cray machine.

Installation issue: geopm #26003 
https://github.com/spack/spack/issues/26003

Spack integration with geopm was a task on one of the projects with LLNL, at the time I took on the task. 
After having the initial version of geopm ( up to geopm1.1) on there working, I have not looked into this.

Since this is not the primary (or even recommended mode of installation according to geopm's readme) I'm not sure if this is a priority. But it may be an interesting platform, therefore figuring out the issue might be interesting to engage with.

Thanks,
--Matthias

**Comment by cmcantalupo** [comment]
Thanks for bringing this to our attention @maiterth!  I have left a  note on the spack issue.  
https://github.com/spack/spack/issues/26003#issuecomment-921839007

**Comment by cmcantalupo** [comment]
#1875

**Comment by bgeltz** [comment]
I cannot repro the issue described in https://github.com/spack/spack/issues/26003#issuecomment-921839007 just yet, but I did identify a few things around building the Fortran code that I just put fixes up for.

It's all in PR #1875 right now.

**Comment by cmcantalupo** [comment]
Done criteria:
- [ ] Working recipes for all packages: covering all installed content from geopm service and base directory
- [ ] Recipes support building from release tag and also from an un-tagged version of the dev branch
- [ ] Pull request has been submitted to upstream Spack repo
