### ISSUE TITLE
Ensure config.h is always included

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#1890]
Our build scripts generate a config.h header, containing macro definitions based on the build configuration. This header must be included before any other header, but sometimes it doesn't get added, which may result in unexpected build outcomes (e.g., due to hitting the wrong part of an `#ifdef`).

One method to ensure this header is included could be to add some build or test automation that returns an error when the header is missing.

Another method may be to include the header automatically by compiler command-line options instead of manually in each .c or .cpp file that might need it.  https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html documents a `-include <file.h>` option that could serve this purpose. It looks like this option also works on icc and clang.

**Comment by cmcantalupo** [comment]
https://github.com/geopm/geopm/commit/7e2dab1024ea6b4e832d2dd1978093f5897857cd
