### ISSUE TITLE
Create a pull request against openhpc to update msr-safe spec file

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1897]
> estimate 2

Relates to #1891 

Done criteria:
- [x] Test of install / uninstall of RPM on SLES 15 sp2 system
- Done as a part of https://github.com/LLNL/msr-safe/pull/93
- [x] New pull request open with openhpc
- https://github.com/openhpc/ohpc/pull/1366

**Comment by bgeltz** [comment]
PRs opened today:
https://github.com/LLNL/msr-safe/pull/93
https://github.com/openhpc/ohpc/pull/1366
