### ISSUE TITLE
GEOPM python agent reports do not contain accumulated signals from the full run

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#1922]
**Describe the bug**
I tried to run a few-seconds-long workload with an agent under a 1-second control loop. Expected run time is part-way through a second. Instead, reported run time is rounded down to the last time the control loop was executed.

**GEOPM version**
1.1.0+dev1547gbab68e0a

**Expected behavior**
A workload takes around 2.5 seconds to complete. I expect the time accumulated from the agent's update() calls to sum near 2.5.

**Actual behavior**
Accounted time (and all other report metrics) depends on the agent's sample period.

| Sample Period | Reported Time |
| ----------------|------------------|
| 0.05 s | 2.5498 s |
| 0.5 s | 2.5002 s |
| 1 s    | 1.9998 s | 

**Error messages produced**
No error messages are produced.

**Additional context**
runtime.py probably needs to read signals and call `agent_.update()` when the popen'd process terminates.

**Comment by fkeceli** [comment]
+1 for this request. My suggestion would be to call update right before the app starts and right after it ends, in addition to the calls during the execution.

**Comment by cmcantalupo** [comment]
I think this was fixed prior to 2.0

**Comment by cmcantalupo** [comment]
No more python agents
