### ISSUE TITLE
Final code cleanup

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#193]
Before beta release, do some last-minute clean up in the code:
- [ ] Alphabetize all lists
- [ ] Run astyle check
- [x] All files should have include guards.
- [x] All files should have config.h.
- [x] Check all const correctness.
- [x] Add or delete copy constructors as appropriate. Also check virtual destructors.
- [x] Change protected sections to private where possible.  Most of these should have been private.

**Comment by cmcantalupo** [comment]
ABC and astyle will be applied after tag.
