### ISSUE TITLE
Contribution instructions refer to a dead link on the GEOPM website

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#1930]
I tried to follow the "Contribution instructions" link on the geopm.github.io. I expected to be directed to https://github.com/geopm/geopm/blob/dev/CONTRIBUTING.rst. Instead I received a 404 error from attempting to reach the old CONTRIBUTING.md file.

**Comment by dannosliwcd** [comment]
I just noticed that page also has a stale link to the project's Travis CI pipeline. I guess that should point to the GitHub Actions pipeline now.

**Comment by cmcantalupo** [comment]
The main page now points to the sphinx documentation.  The legacy page is at https://geopm.github.io/geopm and out-of-date page links have been removed.
