### ISSUE TITLE
If a GPU driver is not present after building with --enable-nvml/levelzero GEOPM will not function

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#1952]
**Describe the bug**
Building on a head node with the appropriate GPU libraries but without GPUs results in an error such as:
```
~/geopm_public_lhlawson> ./geopmread
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: LevelZero::LevelZeroImp: LevelZero Driver failed to initialize. Level Zero Error: ZE_RESULT_ERROR_UNINITIALIZED: at geopm/src/LevelZero.cpp:62                                                                                                 Aborted (core dumped)
```
**GEOPM version**
1.1.0+dev1567gc9a848c8

**Expected behavior**
The accelerator topo should handle the exception and default to the behavior of the Null accelerator topo (i.e. no GPUs)

**Actual behavior**
Throw from LevelZero.cpp (or NVMLDevicePool.cpp) leading to a core dump.

**Error messages produced**
```
~/geopm_public_lhlawson> ./geopmread
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Runtime error: LevelZero::LevelZeroImp: LevelZero Driver failed to initialize. Level Zero Error: ZE_RESULT_ERROR_UNINITIALIZED: at geopm/src/LevelZero.cpp:62                                                                                                 Aborted (core dumped)
```

**Comment by cmcantalupo** [comment]
Note:

The exception handling for the LevelZeroIOGroup failing to load is here:

https://github.com/geopm/geopm/blob/dev/service/src/PlatformIO.cpp#L83-L95

but there is no equivalent exception handling in AcceleratorTopo.cpp.
