### ISSUE TITLE
Add chown to SharedMemory C++ class, uid/gid getters to Helper.cpp

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#1960]
> estimate 2
Parent story: #1857
Related task: #1860

Done criteria:
1. SharedMemory can be chowned from one uid/gid to another.
2. The UID and GID can be queried from the PID.

This is all necessary to get the shmem segments for batch server communication up and running with the right permissions and owners.

- [x] Unit tests added for new class methods except: non-test
      constructors, private methods or classes that provide a
      last-level-abstraction of an external dependency (e.g.
      SDBus or NVMLDevicePool)
- [x] Non-exempt methods with logic branches have multiple
      tests
- [ ] ~Mock objects derived from class have methods added~ No mocks.
- [x] New public methods have doxygen comments describing
      behavior, inputs, outputs and exceptions raised

**Comment by cmcantalupo** [comment]
```
./service/src/geopm/SharedMemory.hpp:76:26: note: unimplemented pure virtual method 'chown' in 'MockSharedMemory'
```

Indeed there are mocks of the SharedMemory object.  When adding new methods to a class that has a mock, the mock must be updated.

**Comment by bgeltz** [comment]
Yep.  I definitely missed that because the mock is in the base dir, and the implementation is in the service dir.  Thanks for pointing that out.
