### ISSUE TITLE
Switch to using a pipe or fifo to communicate ready/read/write messages (new implementation required, and file descriptor will need to be passed through DBus to enable translation.

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#1972]
> estimate 1

- [x] Research how to pass a file descriptor from the batch server to the client probably through the DBus mechanism

Prior to fork call, geopmd process creates a pipe and this file descriptor will be inherited by the forked process.  The geopmd process can then use the DBus mechanism to pass the file desciptor to the client process.  The client and the forked geopmd process can then use the pipe to send status updates.

sd_bus documentation:
https://www.freedesktop.org/software/systemd/man/sd_bus_message_read.html
SD_BUS_TYPE_UNIX_FD

Not yet supported in dasbus:
https://github.com/rhinstaller/dasbus/issues/65

see linked PR which shows other PRs from @wdouglass that are WIPs for supporting this feature in dasbus.

**Comment by wdouglass** [comment]
Hey! saw you guys mentioned me. 
If you don't mind using some github-rando fork until i can get my features merged, you can try my dasbus version at https://github.com/wdouglass/dasbus/tree/unixfd-support

I've been using that branch for a couple of weeks, and it's been working for me. If you guys have feedback before it gets merged, it'd be much appreciated!

**Comment by Krebrov001** [comment]
> Research how to pass a file descriptor from the batch server to the client probably through the DBus mechanism

We don't have to do this any more because we are using the fifo now.

**Comment by cmcantalupo** [comment]
Thanks @wdouglass! 

For our use case, mkfifo(3) was a reasonable way to pass the pipe file descriptor, and we didn't end up going through DBus.
