### ISSUE TITLE
generic header in Tracer.cpp

### ISSUE THREAD

**Issue by milpuz** [geopm/geopm#200]
In Tracer.cpp if we want to change header we would need to hard code new entries. More generic way would be required where maybe (1) some of that information is encoded somehow in telemtery signal or (2) maybe the header should be build beased on which IOGroups has been loaded.

An example of this requirement is in PowerPC port at https://github.com/milpuz/geopm where we also want to report GPU energy consumed. This change also requires change in geopm_message.h

**Comment by cmcantalupo** [comment]
This is the same issue as here:

https://github.com/geopm/geopm/issues/196

We are working to make the trace output a function of either (a) all of the signals that have been pushed onto the PlatformIO stack, or (b) a user configurable list of signal names and domains.   I think that we will do (a) first, but (b) might be pretty useful.
