### ISSUE TITLE
Introduce new C++ class: FixedFrequencyAgent

### ISSUE THREAD

**Issue by scoumeri** [geopm/geopm#2009]
> estimate 1
Parent [feature/story]: #2008 

Introduce new C++ class FixedFrequencyAgent with the following features:
- Ability to set a fixed frequency for the accelerator, cpu and uncore domains
- NaN for the accelerator assigns it to the max accelerator frequency
- NaN for the cpu assigns it to the current cpu frequency
- NaN for the uncore assigns to the current uncore MAX_RATIO and MIN_RATIO

Done criteria:

- [ ] Pure virtual interface class has been added with factory method
- [ ] Unit test constructor provides dependency injection
- [ ] Unit tests added for all class methods except: non-test
      constructors, private methods or classes that provide a
      last-level-abstraction of an external dependency (e.g. SDBus or
      NVMLDevicePool)
- [ ] Non-exempt methods with logic branches have multiple tests
- [ ] All dependency classes have already been merged
- [ ] All public methods have doxygen comments describing behavior,
      inputs, outputs and exceptions raised
- [ ] Implementation file has `#include "config.h"`

**Comment by avilcheslopez** [comment]
Closing this in favor of: #2697
