### ISSUE TITLE
hard-coding of plugin_desc

### ISSUE THREAD

**Issue by milpuz** [geopm/geopm#201]
In Controller.cpp platfrom for plugin_desc is hard coded to rapl, but for Power we need to use different plugin, namely occ so the only way to fix this now is to hardcoded using ifdefs. Also this is hard coded in GlobalPolicy.cpp as well when setting m_platform. 

Should this be replaced at one point with IOGroup?

**Comment by cmcantalupo** [comment]
Yes, IOGroups will fix this problem.
