### ISSUE TITLE
Improve unit test coverage for ServiceIOGroup and BatchServer

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2016]
> estimate 2

The ServiceIOGroup and BatchServer have some negative test cases missing, and so there is not good coverage of exception management.  

Done criteria:

- [x] Pull request that improves coverage is merged
- [x] Test cases are added that cover exceptions

**Comment by Krebrov001** [comment]
Pull request #2007 was merged into `dev`.
