### ISSUE TITLE
when Exception is thrown it does not propagate

### ISSUE THREAD

**Issue by milpuz** [geopm/geopm#203]
When throwing Exception in code it doesn't propagate properly and when GEOPM fails/hangs it is not clear which Exception was thrown? 

More specific example in PowerPC port would be from PowerPlatformImpl class where we try to, for example, read whether file /sys/devices/system/cpu/occ_sensors/chip0/chip-energy exists. If it doesn't exist we throw Exception, but the message from exception is nowehere recorded and application just hangs.

**Comment by cmcantalupo** [comment]
All exceptions created behind a C interface are converted to error return codes.  If geopm is configured with --enable-debug then the exception messages are printed before the C interface returns.  Printing all exceptions thrown is helpful in almost all cases unless the end user is handling the error code from the C interface, but as a library we want to avoid spurious printing.

In the context of using GEOPM as a runtime and not as a library, all unhandled exceptions that occur must be printed.  There are many places during the execution of the controller where exceptions not printed unless --enable-debug is on.  This will cause a lot of confusion until it is fixed.  We generally use --enable-debug to work around this issue, but this also compiles GEOPM without optimization.
