### ISSUE TITLE
transforming rank data when control domain is not package

### ISSUE THREAD

**Issue by milpuz** [geopm/geopm#205]
Inside of a method to do transform_rank_data() in Platform.cpp there is a check for GEOPM_DOMAIN_PACKAGE which means that if power_control_domain() returns anything else apart from it it will not add data to telemetry variable. 

Is this expected behavior? What is supposed to happen if control domain is CPU, for example?

**Comment by cmcantalupo** [comment]
This is a shortcoming of the original Platform/PlatformImp solution:

https://github.com/geopm/geopm/issues/4

The solution for this problem using the PlatformIO solution is targeted for break down here:

https://github.com/geopm/geopm/issues/191

and we will be working on this soon.
