### ISSUE TITLE
throttle_limit_mhz() semantics

### ISSUE THREAD

**Issue by milpuz** [geopm/geopm#206]
What is the meaning of throttle_limit_mhz() and what is expected behavior of the method on non-Intel platforms? 

In PowerPC port we return the same value as returned by KNL, namely 0.5.

**Comment by dianarg** [comment]
This information can also be obtained by parsing the frequency from the trace.  The throttling frequency is architecture-dependent.

**Comment by bgeltz** [comment]
This API has been removed.
