### ISSUE TITLE
Add feature to ActiveSessions that will enable atomic session file creation

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2079]
> estimate 2

- [x] Make sure permissions are least required privilege before moving them
- [x] Test that they parse to the same values written
- [x] Create temporary files with unique ID

**Comment by bgeltz** [comment]
This is really about writing everything into /tmp, which seems to not be the proper approach.

This should probably be closed as will-not-fix.

**Comment by cmcantalupo** [comment]
Instead we are creating temporary files in /var/run/geopm-service, this issue can be considered to track this feature.
