### ISSUE TITLE
parsing lscpu output in presence of SMT

### ISSUE THREAD

**Issue by milpuz** [geopm/geopm#208]
There is validation check at https://github.com/geopm/geopm/blob/21b435f15b1810c865f3d234397b72a1ceab55e4/src/PlatformTopo.cpp#L227 that multiples number of sockets with number of cores per socket with threads per core and compares the value with number of CPUs obtained from lscpu output. When SMT is disabled on PowerPC the output from `lscpu -x` is:

```
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                160
On-line CPU(s) mask:   0x101010101010101010101010101010101010101
Off-line CPU(s) mask:  0xfefefefefefefefefefefefefefefefefefefefe
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Model:                 1.0 (pvr 004c 0100)
Model name:            POWER8NVL (raw), altivec supported
CPU max MHz:           4023.0000
CPU min MHz:           2394.0000
Hypervisor vendor:     (null)
Virtualization type:   full
L1d cache:             64K
L1i cache:             32K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0x1010101010101010101
NUMA node1 CPU(s):     0x101010101010101010100000000000000000000
```

In this case above validation would fail because terms do not multiply to 160 but to 20. To fix this issue the on-line CPU mask should be used to count number of CPUs instead of CPU(s) number.

**Comment by milpuz** [comment]
The below commit counts number of online CPUs and uses it to test when reading from CPU(s) fails:

https://github.com/milpuz/geopm/commit/5b0cb38a6c47e821a001ad45f800473a82b4d2c0#diff-d76a1eb2df16d63ba60388107aad4b3a

**Comment by bgeltz** [comment]
The loop here:
https://github.com/milpuz/geopm/commit/5b0cb38a6c47e821a001ad45f800473a82b4d2c0#diff-d76a1eb2df16d63ba60388107aad4b3aR241

Should be implemented more like this one:
https://github.com/geopm/geopm/blob/dev/src/PlatformTopo.cpp#L321

I'll be cooking up a patch for this shortly.

**Comment by bgeltz** [comment]
Patch is up for review here:
https://review.gerrithub.io/#/c/geopm/geopm/+/409080/
