### ISSUE TITLE
Design Kontroller run algorithm

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#215]
The new implementation of the Controller, called Kontroller, will delegate most responsibilities to several sub classes:
ManagerIO (#213)
ApplicationIO (#211)
KontrollerIO (#212)
Agent (replacing Decider, #189)
Reporter (#214)
Tracer (#196)

**Comment by cmcantalupo** [comment]
https://github.com/dianarg/geopm/blob/dianarg-kontroller/src/Kontroller.cpp
