### ISSUE TITLE
Processes not connecting with controller

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#217]
When there are some CPUs listed by Linux as offline, the controller will not properly connect with the application.  I believe this is due to using the number of online CPUs rather than configured CPUs for creating the CPU -> MPI rank map.

@milpuz Does the patch below fix the issues you are seeing?
<https://github.com/cmcantalupo/geopm/commit/0066ed1827fbb8912607c6658651e1a49c3005e7>
<https://review.gerrithub.io/#/c/406114/>

I noticed that you added an API for configured CPUs in your port as well.  I think that we don't actually care about number of online CPUs, rather changing the geopm_sched_num_cpu() to return configured CPUs should work in all use cases.

**Comment by milpuz** [comment]
@cmcantalupo when this issue was originally raised the problem was that each application rank was not affinitized to a distinct set of CPUs. This was actually observed with SMT = 1 and also SMT > 1. I am yet to check what happens when SMT > 1 and whether this patch is required.
