### ISSUE TITLE
As a user of PlatformTopo I would like a less ambiguous domain than "accelerator"

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2171]
**Is your feature request related to a problem? Please describe.**
The current support for the "accelerator" domain in PlatformIO is done through the LevelZeroIOGroup and the NVMLIOGroup.  These are used to support GPU products.  There are other accelerator products that may be available on a platform, and a less ambiguous name for this PlatformTopo domain will enable future features.

**Describe the solution you'd like**
Rename **all "accelerator" strings in the repository** to "gpu" in a case sensitive way.  In particular the GEOPM_DOMAIN_ACCELERATOR which is part of the geopm_topo_e enum will be renamed GEOPM_DOMAIN_GPU.  In the future we may add support for other accelerator types.  

**Describe alternatives you've considered**
We could leave it as is, but it will be very difficult to change after the version 2.0 release. 

**Additional context**
Related to #1671

**Comment by cmcantalupo** [comment]
The following changes were discussed today for the geopm_domain_e and related strings:

```
Gpu -> GPU
BOARD_MEMORY -> MEMORY
BOARD_ACCELERATOR -> GPU
PACKAGE_ACCELERATOR -> PACKAGE_INTEGRATED_GPU
PACKAGE_MEMORY -> PACKAGE_INTEGRATED_MEMORY
```

**Comment by Krebrov001** [comment]
```
BOARD_NIC -> NIC
board_nic -> nic
PACKAGE_NIC -> PACKAGE_INTEGRATED_NIC
package_nic -> package_integrated_nic

BOARD_MEMORY -> MEMORY
board_memory -> memory
PACKAGE_MEMORY -> PACKAGE_INTEGRATED_MEMORY
package_memory -> package_integrated_memory

BOARD_GPU -> GPU
board_gpu -> gpu
PACKAGE_GPU -> PACKAGE_INTEGRATED_GPU
package_gpu -> package_integrated_gpu

BOARD_ACCELERATOR -> GPU
board_accelerator -> gpu
PACKAGE_ACCELERATOR -> PACKAGE_INTEGRATED_GPU
package_accelerator -> package_integrated_gpu

accelerator -> gpu
Accelerator -> GPU
ACCELERATOR -> GPU
aCCELERATOR -> GPU

accel -> gpu
ACCEL -> GPU
Accel -> GPU
aCCEL -> GPU
```
