### ISSUE TITLE
Generating traces using LevelZero Sysman signals requires ZES_ENABLE_SYSMAN to be set on the command line/ENV

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#2205]
**Describe the bug**
I tried to trace an application and I expected the ZES_ENABLE_SYSMAN=1 in LevelZero.cpp to be sufficient.  Instead it resulted in signal not found/supported issues from LevelZero Sysman until ZES_ENABLE_SYSMAN was set on the command line.  

**GEOPM version**
 geopmread -v
1.1.0+dev1888ge44df591

**Expected behavior**
ZES_ENABLE_SYSMAN should either need to be set on the command line/in the user env for both geopmread and using agents, or not need to be set for both behaviors.

**Actual behavior**
Working: 
- geopmread GPU_POWER board 0
- ZES_ENABLE_SYSMAN=1 geopmread GPU_POWER board 0
- ZES_ENABLE_SYSMAN=1 geopmlaunch impi -n 1 -ppn 1 --geopm-report=foo  --geopm-trace=bar --geopm-trace-signals=GPU_POWER@board -- geopmbench

Not working:
-  geopmlaunch impi -n 1 -ppn 1 --geopm-report=foo  --geopm-trace=bar --geopm-trace-signals=GPU_POWER@board -- geopmbench

**Error messages produced**
Error: <geopm> Invalid argument: PlatformIOImp::format_function(): unknown how to format "GPU_POWER": at src/PlatformIO.cpp:700

**Additional context**
This same issue will arise for ZET_ENABLE_METRICS.  And the various variants of the ZE*_* environment variables.  As of now there are:
- 2 ZES_ENABLE_SYSMAN variants (normal and LOW_POWER) - documented [here](https://spec.oneapi.io/level-zero/latest/sysman/PROG.html)
- 4 Tools & Metrics ENV variables - documented [here](https://spec.oneapi.io/level-zero/latest/tools/PROG.html)
- 3 Affinity variables - documented [here](https://spec.oneapi.io/level-zero/latest/core/PROG.html#environment-variables)

Guessing at the correct config or usage when the end user has not provided varying combinations of these may cause issues (i.e. setting ZES_ENABLE_SYSMAN when they meant to use ZES_ENABLE_SYSMAN_LOW_POWER, or setting ZET_ENABLE_METRICS when the user didn't realize it may cause a perf impact).  It may be better to simply check for the allowed settings for GEOPM and error/warn the user if they're not found.

**Comment by cmcantalupo** [comment]
Remove calls to setenv() within LevelZeroIOGroup, and add documentation for end user about requirement to set environment variable before loading libgeopmd.so.  Add additional documentation about how to set this environment variable in the geopm.service systemd unit file.
