### ISSUE TITLE
The HPC runtime fails to build with --disable-docs when nothing has been built in the service directory

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#2236]
**Describe the bug**
I tried to use the --disable-docs option to build the HPC runtime on a system that already had a system-level installation of the GEOPM service. Since the service was not already installed, I did not run a build in the GEOPM service directory.

The runtime build fails with the following error:
```
make[1]: *** No rule to make target 'man/GEOPM_CXX_MAN_Agent.3', needed by 'all-am'.  Stop.
```

While #2235 fixes this issue for the case where man pages are built in the service, the issue still occurs when there is no service build.

**GEOPM version**
1.1.0+dev1917g7f9ed5b3

**Expected behavior**
The build succeeds. It would be acceptable for there to be no documentation output with `--disable-docs`, or there could be placeholder documentation from the raw documentation source.

**Actual behavior**
The build fails.

Relates to #2215 

**Workaround**
```bash
mkdir -p ~/geopm/service/docs/build/man
for f in ~/geopm/service/docs/source/*.[1-9].*rst; do cp "$f" ~/geopm/service/docs/build/man/$(basename "${f%.*}"); done
ln -s ~/geopm/service/docs/build/man ~/geopm/man
<re-run make>
```

**Comment by bgeltz** [comment]
My workaround was slightly different for building out of a different location:
```
cd ${GEOPM_SOURCE}/service
mkdir -p docs/build/man
for f in ./docs/source/*.[1-9].*rst; do cp "$f" ./docs/build/man/$(basename "${f%.*}"); done
# The symlink in the root dir now maps properly so nothing else is needed.
```
