### ISSUE TITLE
Add environment variable and necessary logic to handle the sample output to the resource manager.

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#225]
This should compliment geopm_env_policy().

There are 2 interrelated command line tools needed to test this new functionality:

1. geopmagent

2. geopmendpoint

https://geopm.github.io/man/geopmendpoint.1.html

geopmagent -p default,POLICY1,...
geopmendpoint -p default job-321

To populate the default values, the Agent API will be modified to provide callback functions in the plugin factory registration function.

A new API will be added to get the default values:

    int geopm_agent_policy_default(
        struct geopm_endpoint_c *endpoint, 
        const double *policy_array);

The result from geopm_agent_policy_default() will be modified and passed to geopm_endpoint_agent_policy() or geopm_agent_policy_json().

**Comment by bgeltz** [comment]
This task should change slightly.  @cmcantalupo is thinking something like the following:

1. Add GEOPM_ENDPOINT env var handling that will serve as part of the base name for the policy and sample files.

2. Policy file will be something like: /geopm-shm-${GEOPM_ENDPOINT}.policy

3. Sample file will be something like /geopm-shm-${GEOPM_ENDPOINT}.sample

If GEOPM_POLICY is set to a JSON file, use that.  GEOPM_POLICY should not be able to create shmem regions.  Should not be able to read a policy from JSON and write samples to shmem.

It's either read the policy and write the samples to shmem, or read the policy from JSON and do not provide the sample data to anyone.

**Comment by bgeltz** [comment]
There are 2 things that appear conflated here:  reading and writing the policy from wither JSON or shmem, and having default agent parameters available on request.

**Comment by dianarg** [comment]
Reopening to address the following: 
- GEOPM_POLICY will be used for file policies
- GEOPM_ENDPOINT will be used for the endpoint shmem prefix that provides a policy
- GEOPM_ENDPOINT takes precendence *unless* GEOPM_ENDPOINT is in the environment default only but the user environment provided GEOPM_POLICY.  Normal rules for environment override still apply.

This patch covers this change: https://review.gerrithub.io/c/geopm/geopm/+/471413

**Comment by dianarg** [comment]
WW45: Under review here: https://review.gerrithub.io/c/geopm/geopm/+/471413
