### ISSUE TITLE
Modify configuration to scan only source code that is installed

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2258]
> estimate 1
Parent story: #2219

Scans should cover

- geopm/src
- geopm/tutorials
- geopm/scripts/geopmpy
- geopm/service/src
- geopm/service/geopmdpy

Done criteria:
- [ ] Automated scans to not flag issues in test code or other non-installed source

**Comment by bgeltz** [comment]
Not possible for keyword scanner or origination scanner.

Continuing with remaining static analysis configs.
