### ISSUE TITLE
GEOPM App Integration build scripts fail for apps with GEOPM markup added

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#2298]
**Describe the bug**
I tried to build AMG, PENNANT, and MiniFE and I expected the existing build.sh script to function instead the patches adding GEOPM region markup caused build failures

**GEOPM version**
1.1.0+dev2023g90214fa2

**Expected behavior**
./build.sh should build the workloads in the integration/apps directory without error

**Actual behavior**/**Error messages produced**
```
mpiicc -o timing.o -c -I.. -O2 -DTIMER_USE_MPI -DHYPRE_USING_OPENMP -fopenmp -DHYPRE_HOPSCOTCH -DHYPRE_USING_PERSISTENT_COMM -DHYPRE_BIGINT -xCORE-AVX2 -I/home/daniel/build/geopm/include -DGEOPM timing.c timing.c(166): error: identifier "GEOPM_REGION_HINT_UNKNOWN" is undefined
geopm_prof_region(name, GEOPM_REGION_HINT_UNKNOWN, g_geopm_rid + time_index); ^
compilation aborted for timing.c (code 2)
```

**Additional context**
An additional reason to implement #2293

**Comment by bgeltz** [comment]
All code that needs to use the hints must now include ```#include <geopm_hint.h>``` in order to get access.  This change should be made across the entire codebase.

Apps that need to have their markup patches updated within the GEOPM codebase include:
* AMG
* Pennant
* CoMD
* miniFE
