### ISSUE TITLE
Implement the geopm_endpoint_*() APIs

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#231]
Adding geopm_endpoint.h header to install, but there is no implementation

**Comment by dianarg** [comment]
Needs to be broken down: @cmcantalupo 
- Get additional feedback on interfaces (@sidjana)

**Comment by dianarg** [comment]
Implement the interface used by geopmd to read and write shared memory with the controller.  The controller will use the C++ class.  See #666

**Comment by dianarg** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/465841
