### ISSUE TITLE
Add chapter 7 man pages for all of the IOGroups

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2314]
> estimate 3

Parent story: #1670 
Relates to #1671 

The goal is to provide user documentation for the signals and controls provided by PlatformIO split out into a man page per-IOGroup.  The purpose of these man pages is to describe the signals and controls can be provided by the IOGroup.  This information may be used in conjunction with any of the PlatformIO interfaces, including command line tools like geopmread(1).  Note that unlike the chapter 3 pages, these manuals are for end users, not developers.

- The modification is to user documentation
- The change is a addition
- The reason for the change is there is no other man page that describes signals and controls available from PlatformIO
- The documentation component to change is geopm service man pages

**Comment by lhlawson** [comment]
- [ ] SST-IO, TimeIO, CPUInfo - Asma
- [ ] CNLIO - Daniel
- [ ] MSRIO - Alejandro
- [ ] DCGM, LevelZero, NVML - Lowren

**Comment by bgeltz** [comment]
- [ ] ServiceIO - Brad
- [ ] ProfileIO - Brad
