### ISSUE TITLE
MSR writes with the stock MSR driver no longer work by default with kernels >= 5.9

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2461]
**Describe the bug**
I tried to write to a MSR with the stock MSR driver and I expected it to succeed instead an error was raised.

**GEOPM version**
```41d68f17```

**Expected behavior**
MSR writes through GEOPM work as expected.

**Actual behavior**
MSR writes through GEOPM fail and produce the following message in the journal:
```
Jul 14 14:42:48 compute_node_1 kernel: msr: Write to unrecognized MSR 0x38f by geopmd (pid: 42577). Please report to x86@kernel.org.
```

**Additional context**
Starting with Linux kernel 5.9, writes to MSRs are disallowed by default:
https://www.phoronix.com/scan.php?page=news_item&px=Linux-Filter-Tightening-MSRs
https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?h=x86/misc&id=a7e1f67ed29f0c339e2aa7483d13b085127566ab

Viable workarounds are to set ```msr.allow_writes=on``` on the kernel command line at boot, or if the system is already booted use the following sysfs entry:
```
echo "on" > /sys/module/msr/parameters/allow_writes
```

*NOTE:* This does not apply when using the msr-safe kernel driver.

**Comment by cmcantalupo** [comment]
Do effectively the following, but in python as part of geopmd startup:

```
if [[ ! -e /dev/cpu/0/msr_safe ]] && [[ -e /sys/module/msr/parameters/allow_writes ]]; then
  echo "on" > /sys/module/msr/parameters/allow_writes
fi
```
Additionally, keep track of this change, and revert the change when the geopm service is stopped.
