### ISSUE TITLE
Prove package scoped MSR based controls are working

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#249]
The geopmread/write testing is exposing a potential issue where writing a control to a package scoped MSR may not actually result in the desired change at the CPU level.  The msr_hsx.cpp file shows IA32_PERF_STATUS and PERF_CTL as being M_DOMAIN_CPU vs. msr_knl.cpp shows them as M_DOMAIN_PACKAGE.  The fact that they're package in the case of KNL may be part of the culprit.

This may result in a change to all our package scoped controls such that they write to all CPUs instead of just one.

Controlling frequency via IA32_PERF_CTL and IA32_PERF_STATUS were used to uncover this.

**Comment by dianarg** [comment]
Confirmed that setting frequencies for individual CPUs works on mcfly (SKX).  On quartz, I am not seeing the frequencies I expect. 

On KNL, setting package frequencies works with this patch: https://review.gerrithub.io/#/c/geopm/geopm/+/411494/

**Comment by dianarg** [comment]
Package scoped controls fixed by: c2e6a9199f89e4984c74d2640e7821551f518b13
CPU controls changed to core scope by: 1e659437f8665364df7dc76c64da8aac3b900afd
