### ISSUE TITLE
Improve integration testing that save/restore occurs in all cases that use a batch server

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2512]
> estimate 5
Parent story: #2014

Enumerate all ways that a GEOPM session may end, and ensure that in all cases the service provides proper save/restore behavior.

Prerequisite work:
- [x] #2549

New tests:
- [x] #2514
- [x] #2535
- [x] #2536
- [x] #2537
- [x] #2538
- [ ] #2539`
- [x] #2540

**Comment by bgeltz** [comment]
#2535, #2536, #2539, and #2540 all require a new test helper script to be written that provides privileged operations for sending signals to processes that the test user does not own.
