### ISSUE TITLE
GEOPM_DEBUG_ATTACH broken for non-numeric values

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#260]
When attempting to utilize GEOPM_DEBUG_ATTACH with a non-numeric value, the Environment parser throws:

terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Invalid argument: Environment::Environment(): Value could not be converted to an integer: at geopm/src/Environment.cpp:218

Afterward, the controller exits without ever coming up fully.  The documentation here:

https://github.com/geopm/geopm/blob/dev/ronn/geopm.7.ronn

Suggests that: If set, but not to a numerical value then all ranks are trapped.  The functionality appears broken.

**Comment by bgeltz** [comment]
```
geopmsrun -N 1 -n 4 --geopm-debug-attach --geopm-ctl=process --geopm-report=t6_report --geopm-trace=t6_trace -- ./tutorial_6 tutorial_6_config.json
<geopmpy.launcher> --geopm-ctl must be one of: "process", "pthread", or "application"
```

That should work.  If I pass a number it will trap that rank.  If I pass something like true, it still barfs:

```
geopmsrun -N 1 -n 4 --geopm-debug-attach true --geopm-ctl=process --geopm-repo
rt=t6_report --geopm-trace=t6_trace -- ./tutorial_6 tutorial_6_config.json
...
terminate called after throwing an instance of 'geopm::Exception'
  what():  <geopm> Invalid argument: Environment::Environment(): Value could not be converted to an integer: at geopm/src/Environment.cpp:218
...
```

**Comment by sidjana** [comment]
TODO: Also, change the error message to indicate the name of the env. variable that triggers the message

**Comment by dianarg** [comment]
Change implementation to match documentation.
