### ISSUE TITLE
Build RPMs for the LDMS sampler on surrogate system A

### ISSUE THREAD

**Issue by sidjana** [geopm/geopm#2603]
> estimate 3

Done criteria:
- write a spec file for the surrogate system
- validate operation
- share and present to collaborators

**Comment by cmcantalupo** [comment]
http://mcfly.ra.intel.com/~cmcantal/ovis-geopm-sampler-4.3.8-1.src.rpm
http://mcfly.ra.intel.com/~cmcantal/ovis-geopm-sampler-4.3.8-1.x86_64.rpm
