### ISSUE TITLE
Write parser and generator for the file used by the ConstConfigIOGroup

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2620]
> estimate 1

Done criteria:
Implement and write unit tests for the suggested public methods of the IOGroup:

``std::map<std::string, double> ConstConfigIOGroup::parse_file(const std::string path);``
``void ConstConfigIOGroup::gen_file(const std::string path, const std::map<std::string, double>);``

**Comment by avilcheslopez** [comment]
Closing this issue for now. An implementation for the parse method is provided, but is private at the moment. The understanding is that the intention for these methods is to provide a mechanism for the upcoming node characterization tool for generating the configuration file. The interface for the tool is yet to be defined, so we will revisit the need and interface for these methods at that point.
