### ISSUE TITLE
Remove deprecated Sysman functions

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#2654]
> estimate 1
Parent [feature/story]: #XXXX

The implementation for the LevelZero feature was modified because of deprecation of the interface used. 

Done criteria:

- [ ] Integration tests that cover the feature run and pass
- [ ] Dependencies mocked in unit tests are still valid
- [ ] Documentation changes are not required since this change does
      not modify interfaces or features.

**Comment by bgeltz** [comment]
We don't make any deprecated function calls AFAICT.  The only deprecated usage we have is the ```zes_power_properties_t``` struct, specifically the ``defaultLimit``, ``minLimit``, and ``maxLimit`` fields.  This should be revisited when we implement power controls.
