### ISSUE TITLE
Spell/grammar check all files in the code-base

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2664]
Ensure there are no spelling or grammar errors in the code base.  This includes all source files and documentation (e.g. the main README).

Relates to #2530 insofar as that this could all be done as a CI check.

**Comment by dannosliwcd** [comment]
Might use  [codespell](https://github.com/codespell-project/codespell) 

The following command should give a general idea of what needs to change:
```
codespell "--ignore-words-list" "atleast,clos" "--skip=googletest-release*,autom4te.cache,./service/docs/build,./service/contrib,libtool*,ltmain*"
```
