### ISSUE TITLE
64-bit counters are not handled properly

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#267]
Values read from 64-bit counters are not being gathered properly with the MSR object.  The logic to handle those large values and overflows needs to be re-worked.

**Comment by cmcantalupo** [comment]
We need to identify what the requirement is here.  There are 52 bits in the mantissa of a double precision number (plus one implicit bit).  The test that is added by the referenced patch gives more importance to the high order bits of the 64 bit counter than the low order bits.  The double precision representation of 0xFFFFFFFFFFFFFFFF will truncate the low order 11 bits, and the test will fail if all of the high order bits are not equal.  

When calculating differences between counter values, these higher order bits are actually irrelevant.  I'm not sure if anyone cares about the absolute values of Aperf and Mperf (the only 64 bit counters that we support), but rather they will most likely be differencing two measured values.  By this logic, it seems that defining Aperf and Mperf as 52 bit counters (or say 48 bit counters, as they are defined in the current implementation), and using the existing overflow logic to deal with when the counters change in higher order bits, will be more accurate for our users, and will not require any changes to the implementation.  

That is to say, I think the test that you have added introduces a requirement that will make our implementation less accurate for all use cases that I can think of, and requires a change to our current implementation.
