### ISSUE TITLE
As a developer I would like the Activity agents to use ConstConfigIO

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#2698]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when agents put information that could go into ConstConfigIO in the policy.  This puts the burden on users to understand system information vs agent & workload information.

**Describe the solution you'd like**
Update the activity agents to use ConstConfigIO instead of relying upon policy inputs.  This will significantly reduce the policy size for the CPU & GPU CA.

**Describe alternatives you've considered**
Use policy inputs with additional handling for a large number of NAN values that users may not understand.

**Comment by bgeltz** [comment]
Reopening to deal with #2735
