### ISSUE TITLE
PlatformIO aggregated writes assume user has read permission for the target control

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#2707]
**Describe the bug**
I tried to use geopmwrite at board scope on a package-scoped control that I only have write permission to use. The write failed due to a missing signal of the same name (the signal exists, but is not reported by GEOPM since I do not have read access to it).

**GEOPM version**
2.0.0

**Expected behavior**
I expect to be allowed to geopmwrite any control that I have been granted permission to write.

**Actual behavior**
If I geopmwrite at a more coarse domain than the control's native domain, then the write operation fails when I do not also have read permission.

**Error messages produced**
```
geopmwrite SST::COREPRIORITY_ENABLE:ENABLE board 0 0
Error: cannot write control: <geopm> Invalid argument: ServiceIOGroup::signal_behavior(): signal_name SST::COREPRIORITY_ENABLE:ENABLE not valid for ServiceIOGroup: at src/ServiceIOGroup.cpp:313
```

Note that although the error message says it comes from `signal_behavior()`, the text of that message is wrong. The line number is from `agg_function()`. That function is called by PlatformIO when writing at a level more coarse than the control's native domain. The output is used to determine whether the write value should be distributed (for sum types) or broadcast (for other types) across its native domain.

**Workaround**
Write the control in its native domain to avoid executing the function that depends on read permissions.

**Comment by cmcantalupo** [comment]
Pehaps we should change the way the service works so that if write permission is granted, read permission is always also granted.
