### ISSUE TITLE
Error message in service.py is missing fstring specifier

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2768]
**Describe the bug**
When the exception is raised here:
https://github.com/geopm/geopm/blob/dev/service/geopmdpy/service.py#L905

I expected the `api_name` to be filled in, instead `"{api_name}"` appears in the error message.

**GEOPM version**
4fdf753b394dcc4a388cdfe3edfdf37c5bf67cd4

**Comment by bgeltz** [comment]
Already fixed with 33e0feda09
