### ISSUE TITLE
Define mechanism for setting per-node power limits (with or without agents)

### ISSUE THREAD

**Issue by avilcheslopez** [geopm/geopm#2784]
> estimate 3

Done criteria:
- Record notes from arch meeting

**Comment by cmcantalupo** [comment]
Simplest solution:
- Add MSR feature to set node power limit (captured in separate issue already)
- Add a python function that will use the node power limit feature and supporting registers to implement a limit
- Create a resource manager plugin that calls above function based on user input to the launch command line

For future work, it may be benefit users to do the following:
- Modify the PowerGovernor to expose this feature including setting sensible defaults
- Modify the PowerGovernorAgent to have an optional policy value that determine the node power limit
- Modify the enforce_policy() method of PowerGovernorAgent to respect the node limit
