### ISSUE TITLE
GEOPM agent/endpoint integration with slurm

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#280]
Integrate the agent and enpoint interfaces into a slurm plugin.  Related to issue #10, but this is in reference to the specific work being done for SLURM by @r-sakamoto here:

https://github.com/r-sakamoto/power-slurm 

The end goal is to have slurmd call into the interfaces documented here:

https://geopm.github.io/man/geopm_agent_c.3.html
https://geopm.github.io/man/geopm_endpoint_c.3.html

**Comment by dianarg** [comment]
Also related to #610.  If possible, open a new issue for endpoint integration and close this issue @cmcantalupo

**Comment by dianarg** [comment]
Now broken down.
