### ISSUE TITLE
Out-of-tree builds are broken

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2826]
**Describe the bug**
I tried to build the service out-of-tree and I expected it to work instead an error was encountered when the docs build was attempted.

**GEOPM version**
82c336767

**Expected behavior**
The build completes successfully with an RC of 0.

**Actual behavior**
```
$ cd ${GEOPM_SOURCE}
$ git clean -ffdx
$ cd service
$ mkdir obj
$ ./autogen.sh
$ cd obj
$ ../configure --disable-docs
$ make

# lots of output then this failure:

sed -e '/@MSR_JSON_CONTENTS@/ {' \
    -e "r ../src/msr_data_arch.json" \
    -e 'd' -e '}' \
    -e "s/@MSR_JSON_IDENTIFIER@/arch_msr_json/g" \
src/msr_data.cpp.in > src/msr_data_arch.cpp
sed: can't read src/msr_data.cpp.in: No such file or directory
make[1]: *** [Makefile:3930: src/msr_data_arch.cpp] Error 2
make[1]: Leaving directory '/home/bgeltz/git/geopm/service/obj'
make: *** [Makefile:1741: all] Error 2
```

**Comment by dannosliwcd** [comment]
libgeopmd out-of-tree builds are fixed by https://github.com/geopm/geopm/pull/3230 (tested 44f4882cd). libgeopm seems to also work but it is tricky.

With default ./configure options, the linking stage of an out-of-tree build of `libgeopm` fails with
```
./libtool: line 7486: cd: ../../libgeopmd/.libs: No such file or directory
libtool:   error: cannot determine absolute directory name of '../../libgeopmd/.libs'
```

The following seems to work
```
cd libgeopm
mkdir obj
./autogen.sh
cd obj
../configure  --with-geopmd-lib=../../libgeopmd/obj/.libs --disable-geopmd-local
```
