### ISSUE TITLE
Select benchmark applications for scaling run

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#284]
Compile and run tiny size of benchmark application on Theta.

**Comment by cmcantalupo** [comment]
Nekbone, AMG (check with Aniruddha @amarathe84 for large problem size options for AMG), possibly run miniFE.

**Comment by dianarg** [comment]
Nekbone and AMG are both tier 1 benchmarks that give good results with the balancer.  We can also run MiniFE because scripts are ready.
