### ISSUE TITLE
Error message unclear when failures occur when saving controls in the service 

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2844]
**Describe the bug**
I tried to run the service integration tests and I expected no errors instead errors were produced with insufficient information to debug.

**GEOPM version**
2.0.1

**Expected behavior**
Useful error messages to indicate what the underlying problem is with saving controls.

**Actual behavior**
```
Feb 07 16:24:14 <NODE_NAME> geopmd[133013]: RuntimeError: geopm_pio_save_control_dir() failed: <geopm> Runtime error
```

**Additional context**
This specific case was a problem with L0 failing to load properly, but we were still trying to save all the controls.

**Comment by cmcantalupo** [comment]
Seems like this could have been a std::runtime_error raised by std::vector.at() which would cause a missing exception message (last exception raised must be a geopm::Exception to have the what() propagate to the log.
