### ISSUE TITLE
Enable GEOPM on Sunspot system

### ISSUE THREAD

**Issue by avilcheslopez** [geopm/geopm#2850]
> estimate 1

Resolve issue with SST driver (issue on SLES 15 SP3):
- Block SST IOGroup from loading
- Provide support to sysadmin to enable GEOPM service

Done criteria:
- [ ] GEOPM service installed and available for all users of the compute nodes
- [ ] Build HPC runtime on head node

**Comment by bgeltz** [comment]
Deployed
