### ISSUE TITLE
Add intgration test that shows an accurate report generated by a non-mpi application

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2854]
> estimate 1

Done criteria:
- [x] Add simple test for running ~sleep(1)~ sleep(3) ~with libgeopmload.so preloaded~
- [x] Test that runtime is accurate
- [x] Changes are merged into https://github.com/geopm/geopm/pull/2836

**Comment by avilcheslopez** [comment]
Add separate issue:
Add simple test for running sleep(1) **with libgeopmload.so preloaded**
