### ISSUE TITLE
Issue: leftover keys (clean-up in service needs to be more robust)

### ISSUE THREAD

**Issue by avilcheslopez** [geopm/geopm#2881]
Keys: status (one per user), record-log (one per MPI rank/process)

Reproducer
- Run controller in the background
- Run app that attached to the controller
- "Ctrl+C" (sigterm) the app
- Kill controller or kill geopmd
- There should be leftover keys at this point
- Repeat experiment
- Connection will fail because keys already exist

Add negative test to verify fix.

**Comment by bgeltz** [comment]
The existing tests were extended to cover this check.  

A new bug about the session JSON file not being cleaned up was discovered: #2954.
