### ISSUE TITLE
Controller does not restore controls when they are accessed through the service: the ServiceIOGroup does not implement save/restore

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#2892]
**Describe the bug**
I tried to run the static_agent.py tutorial Python agent and I expected controls to be restored to their initial value at the end of the run instead any requested control values persist after the run is complete.

**GEOPM version**
2c8cb6160

**Expected behavior**
```
$ geopmread CPU_POWER_LIMIT_CONTROL board 0
280

$ ./static_agent.py --geopm-report stress-report.report --geopm-initialize-control CPU_POWER_LIMIT_CONTROL=150 -- stress-ng --cpu 44 --taskset 0-43 --timeout 10

$ geopmread CPU_POWER_LIMIT_CONTROL board 0
280
```

**Actual behavior**
```
$ geopmread CPU_POWER_LIMIT_CONTROL board 0
280

$ ./static_agent.py --geopm-report stress-report.report --geopm-initialize-control CPU_POWER_LIMIT_CONTROL=150 -- stress-ng --cpu 44 --taskset 0-43 --timeout 10

$ geopmread CPU_POWER_LIMIT_CONTROL board 0
150
```

**Additional context**
My user does not have direct access to msr-safe, and is leveraging the service for all reading/writing.

The real problem here is that the ServiceIOGroup has no implementation for save_control() or restore_control().  This is what's called on the user's side when they call into pio.save_control() from the runtime.py.

It would be nice if we had a way to trigger the service to do a restore operation without having to close the currently active session.

https://github.com/geopm/geopm/blob/2c8cb6160c21f83ceb8e9eecf3644aac9aa93838/tutorial/python_agents/static_agent.py#L36-L38
The lines above only apply when you have direct access to the IOGroup that provides the control.  If you're relying on the service to provide signals/controls, the service only restores control values when the session ends (e.g. by job termination or logging out of an allocation).

**Comment by cmcantalupo** [comment]
I do not believe that this is unique to the python infrastructure.  The same code path exists for the GEOPM controller.

**Comment by bgeltz** [comment]
I just verified that this is not a problem when using `geopmlaunch` as I was implementing #2918.  The reason is that `srun`, `mpiexec`, etc. do a `setsid` somewhere in their fork-exec logic.  This means that the GEOPM service tracks this new session as opposed to the one corresponding to your terminal in an interactive allocation.  As a result, any controls that are written by an Agent or similar are reverted when the job step ends.
