### ISSUE TITLE
better-collision-error-message

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#29]
In GEOPM_ERROR_TOO_MANY_COLLISIONS error case, error message should suggest that multithreaded calls into geopm_prof_enter() / geopm_prof_exit() may trigger the too many collisions error.

**Comment by sssylvester** [comment]
This is no longer relevant now that the table does not overflow as of I4607cce1c937b17d28a35535795a1d8f8b1d1b82.
