### ISSUE TITLE
OpenHPC: enable cpu-bind option for slurm

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#290]
Modify OpenHPC distribution of SLURM to enable the --cpu-bind option for the srun command line.

**Comment by cmcantalupo** [comment]
@crbaird Issue to track geopm requirements for OpenHPC

**Comment by cmcantalupo** [comment]
@crbaird Issue to track geopm requirements for OpenHPC

**Comment by bgeltz** [comment]
https://github.com/bgeltz/ohpc/commit/76c8ecf2b01fd59c2e592f2b92a29d48a424579f
https://github.com/openhpc/ohpc/pull/821
