### ISSUE TITLE
OpenHPC: Add epilog and prolog use of msrsave

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#291]
Modify slurm prolog to run:

    /usr/sbin/msrsave /tmp/$SLURM_JOB_ID-msrsave.dat

and modify the epilog to run

    /user/sbin/msrsave -r /tmp/$SLURM_JOB_ID-msrsave.dat

so that msr values are restored.

**Comment by cmcantalupo** [comment]
@crbaird Issue to track geopm requirements for OpenHPC

**Comment by cmcantalupo** [comment]
Testing blocked on msr-safe upgrade on mr-fusion and the BIOS setting on mcfly.

**Comment by bgeltz** [comment]
What about PBS pro?  It looks like OpenHPC supports both PBS pro and SLURM...

**Comment by cmcantalupo** [comment]
https://github.com/openhpc/ohpc/pull/853
