### ISSUE TITLE
As a user I would like GEOPM Integration infrastructure to support launching with pals

### ISSUE THREAD

**Issue by asmaalrawi** [geopm/geopm#2912]
Slurm and apirun are supported, there is no pals list.

https://github.com/geopm/geopm/blob/ffe3a377657cfd4edc03e74e35fcd277164df1f0/integration/experiment/util.py#L31-L37

**Comment by lhlawson** [comment]
Some additional info: 
Initial testing with GEOPM_LAUNCHER=pals did not seem to work around this issue, though the script does look for this environment variable.

**Comment by cmcantalupo** [comment]
Pals launcher is not a priority
