### ISSUE TITLE
OpenHPC:  Add -disable-intel-pstate to kernel command line

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#292]
Modify kernel command line on compute nodes in OpenHPC to disable the intel pstate driver.

**Comment by bgeltz** [comment]
It's ```intel_pstate=disable```.

**Comment by cmcantalupo** [comment]
@crbaird Issue to track geopm requirements for OpenHPC

**Comment by bgeltz** [comment]
https://github.com/bgeltz/ohpc/commit/76c8ecf2b01fd59c2e592f2b92a29d48a424579f
