### ISSUE TITLE
Non-MPI app support: reduce app, startup overheads

### ISSUE THREAD

**Issue by avilcheslopez** [geopm/geopm#2947]
> estimate 3

Goals:
- Reduce overhead in part of the code we control
- Consider mitigation measures for overhead in parts of the code we don't control (e.g. reducing number of calls to DBus API, if possible)

Acceptance criteria:
- Do not introduce a regression (measure current overhead in dev branch)
- There is not a specific overhead target. At a high level, the goal is to address overhead issues that are reasonably within our scope. For example, avoid solutions that involve rewriting our code to solve a problem already solved by another library. Migrating to using another library instead of DBus is a potential solution to consider in the future.

**Comment by cmcantalupo** [comment]
GEOPM Controller start up is still around 1.5 seconds but the application overhead has been reduced to 0.3 seconds with 42 proc / controller.
