### ISSUE TITLE
The runtime.rst documentation needs to be updated to reflect non-MPI use

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#2985]
> estimate 1

Also references to libgeopmpolicy were all blindly converted to libgeopm, however the PlatformIO APIs etc are actually located in libgeopmd now.

**Comment by dannosliwcd** [comment]
| Also references to libgeopmpolicy were all blindly converted to libgeopm

One way this manifests in a few rst docs:

```Link with ``-lgeopm`` **(MPI)** or ``-lgeopm`` **(non-MPI)**```
