### ISSUE TITLE
Refactor runtime tutorials such that they start with non-MPI use cases and build up to full MPI use cases

### ISSUE THREAD

**Issue by avilcheslopez** [geopm/geopm#3008]
> estimate 1

- Include non-MPI examples of how to leverage the runtime
- Build up tutorial that leverages the report signals and trace signals
- Shift the showcase agent from power balancer/governor to FrequencyMapAgent
- Add placeholders for all other agents that don't have tutorials (will be addressed in a future task)

**Comment by cmcantalupo** [comment]
We have deleted the runtime tutorials and added documentation to the getting started guide
