### ISSUE TITLE
Command line options --geopm-barrier and --geopm-plugin don't match corresponding environment variable

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#302]
The documentation states that the CLI options are the same as the environment variables but lowercase and with the hyphens replaced with underscores.  This is not true for these options.  Note that --geopm-ctl also does not match, but the option and the environment variable have slightly different behavior.

**Comment by bgeltz** [comment]
Also, GEOPM_RM could/should be renamed to GEOPM_LAUNCHER.
