### ISSUE TITLE
PlatformIO API to return the number of domains for a given signal name

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#303]
A common pattern is to push a signal for every domain index in a domain.  The number of domains is obtained by chaining two calls, e.g. ```platform_topo(platform_io.signal_domain_type(signal_name))```.  It would be convenient for Agent writers to have a PlatformIO method to return the number of domains for a given signal/control.

**Comment by dannosliwcd** [comment]
#639, #640, and #641 were opened as a result of code review on a change for this issue. This issue will no longer be relevant when those issues are addressed.
