### ISSUE TITLE
Debug GEOPM/msr-safe interaction oddities on Theta

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#309]
Certain MSR reads on Theta are causing a permissions denied error when the read is attempted.  At the moment, this is occurring sporadically.  It is always occurring with the same MSR offset when it does manifest.

aprun'ing rdmsr is 100% successful.  This appears to be isolated to something GEOPM is doing.

This may be related to the permission denied error occuring with the latest msr-safe install on Mr. Fusion.

**Comment by dianarg** [comment]
The error that occurs is:

<geopm> Warning: failed to load MSR IOGroup.  GEOPM may not work properly unless an alternate IOGroup plugin is loaded to provide signals/controls required by the Controller and Agent.
The error was: <geopm> Could not write to MSR device: MSRIO::read_msr(): pread() failed at offset 0x38f system error: Permission denied: at geopm/src/MSRIO.cpp:86
Error: <geopm> Invalid argument: PlatformIO::read_signal(): signal name "ENERGY_PACKAGE" not found: at geopm/src/PlatformIO.cpp:466

**Comment by dianarg** [comment]
This issue is still open with Theta admins.  The current workaround is to launch rdmsr on all allocated nodes at the start of a job, collect the list of nodes that failed, and avoid running on those nodes.

**Comment by dianarg** [comment]
This workaround is implemented in the shared base.sh script automatically.
