### ISSUE TITLE
Final release process for 3.0

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#3130]
> estimate 1

- [x] Complete security process
- [x] Write change log
- [x] Bump ABI
- [x] Test: install a package from before 3.0, then upgrade to 3.0 via package manager
- [x] Review all documentation and examples
  - Known Issue: https://geopm.github.io/security.html#provide-a-low-latency-interface mentions `/tmp` usage which is now actually in the geopm run directory
- [ ] Party!

**Comment by bgeltz** [comment]
Tested package manager upgrade flow on ubuntu.

Starting with a v2.0 dev build installed from Chris's PPA, I added the new GEOPM release PPA, and issued ```apt update```.  The upgrade completed successfully.  Afterwards, ```libgeopmd1``` remained installed until I issued ```apt autoremote```, when it was then cleaned up.

The only thing of note was the new warning messages in the journal about the new spot for configuration files:
```
Nov 07 15:14:17 kronos systemd[1]: Stopped Global Extensible Open Power Manager Service.
Nov 07 15:14:17 kronos systemd[1]: Starting Global Extensible Open Power Manager Service...
Nov 07 15:14:17 kronos geopmd[170426]: Warning <geopm-service> Using an old GEOPM configuration directory. The directory at "/etc/geopm-service" is deprecated and may not be used in future GEOPM releases. Migrate configuration data to the directory at "/etc/geopm"
Nov 07 15:14:17 kronos geopmd[170426]: Warning: <geopm> Unable to read MSR configuration from /etc/geopm. Reason: <geopm> Runtime error: Helper::list_directory_files(): failed to open directory '/etc/geopm': No such file or directory: at src/Helper.cpp:146
Nov 07 15:14:17 kronos systemd[1]: Started Global Extensible Open Power Manager Service.
Nov 07 15:14:22 kronos geopmd[170426]: Warning: <geopm> Unable to read MSR configuration from /etc/geopm. Reason: <geopm> Runtime error: Helper::list_directory_files(): failed to open directory '/etc/geopm': No such file or directory: at src/Helper.cpp:146
```

AFAICT, this is all expected.  Closing.
