### ISSUE TITLE
Add policy columns to the power_balancer trace output

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#316]
Add columns to the trace that give the values of the policy that was last passed down.

**Comment by bakerbrandond** [comment]
I'll do this. I'll add it as a patch dependent on my current refactor endeavors. Would rather not have to track a branch or worry about merge conflicts for something so easy

**Comment by cmcantalupo** [comment]
Okay.  I was thinking one column per policy value.

policy_power_cap
policy_step_count
policy_max_epoch_runtime
policy_power_slack

Also the current power limit enforced at the leaf perhaps as the last column:

policy_power_limit

Seems like having a generic solution to add the Agent policy values to the trace might be useful.  I'll look into that briefly.
