### ISSUE TITLE
Require test_power_balancer integration test to be run inside an allocation

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#321]
Currently the test launches 2 jobs, one for the governor followed by one for the balancer.  If the nodes these jobs happen to land on are disjoint and the sets of nodes differ enough wrt manufacturing variance this may cause the comparison of the agents to fail for reasons out of hand of the balancer.

I suggest we skip this test unless it is in an allocation, similar to the test_report_and_trace_generation_application test.

Warning, the proposed test decorator requires SLURM as your resource manager so we may want to explore another option.

**Comment by cmcantalupo** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/421763
