### ISSUE TITLE
Building unit tests fails without --enable-debug

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#323]
Compiling the unit tests with icc/icpc and optimizations is extremely slow or possibly hung.  We should warn if the checkprogs target is built with -O2, or always use -O0.

**Comment by bakerbrandond** [comment]
Another issue regarding this topic is the fact that LOGIC_ERRORS are only thrown in debug.  the GEOPM_EXPECT_THROW macro could be smartened up to handle this properly in the case --enable-debug is not present.

**Comment by dianarg** [comment]
Some warnings like the following are printed:

test/ProfileTableTest.cpp(128): (col. 1) remark: Some OpenMP processing was skipped to constrain compile time. Consider overriding limits (-qoverride-limits).
