### ISSUE TITLE
Remove DRAM measurement from PowerGovneror

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#332]
In the future if we want to impose power caps on the total node power consumption it should be driven by measurements made at the power supply.  In this use case the time window over which power is required to be capped will be quite a bit longer and the latency of power supply measurements can be handled within the context of the long window constraint.

The current implementation of the PowerGovernor does not account for the time window requirement and is trying to react on a time scale that is much shorter than node power capping scenarios would require.  This is driving noise into the system in a way that is detrimental.  Let's table this feature to try to power cap the sum of CPU and DRAM power until the requirements for this feature are clearly defined and a customer identified.  I expect we will actually be trying to cap node or rack power when the constraints are presented not the sum of CPU and DRAM.

**Comment by dianarg** [comment]
https://review.gerrithub.io/#/c/geopm/geopm/+/422910/
