### ISSUE TITLE
Agent::report_region() does not know region_ids to be passed to PlatformIO::sample_region_total()

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#333]
Unless the Agent is expected to keep a set of region ID's that were observed directly by sampling, there is no way for an agent to extend the report with data retrieved by PlatformIO::sample_region_total().  This could be resolved in one of two ways.  Either the PlatformIO should provide an API that returns all observed region IDs, or the Agent should be able to extend the regions in a report by specifying a sample_idx.

**Comment by bgeltz** [comment]
This functionality was moved to RegionAggregator::sample_total.  There's still no way to extract the list of observed regions from this object.
