### ISSUE TITLE
Begin release process with security expert to enumerate new required tasks

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#3345]
> estimate 1

Done criteria:
- [x] Set meeting to discuss
- [x] Enumerate task plan
- [x] Understand fuzzing requirements
- [x] Discuss OpenSSF scorecard: https://securityscorecards.dev/viewer/?uri=github.com/geopm/geopm

**Comment by dannosliwcd** [comment]
There was an open question from planning around what it would take to run geopmd as a regular user (to simplify usage of fuzzing harnesses, which are part of this issue). Draft PR #3348 shows likely files that need to be modified.
