### ISSUE TITLE
Unknown how to set GEOPM_NUM_PROC for apps that fork processes

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#3353]
It may be the case that a user does not want to profile forked processes, but with the current implementation, forked processes will always register for profiling.  This may cause issues if the number of forked processes is unknown to the user running the controller.  In this case it will be unknown how to set GEOPM_NUM_PROCESS

One solution is to never profile forked processes who's parent has already registered for profiling.  An implemenation has been posted to this PR:

https://github.com/geopm/geopm/pull/3358

Note that this would be a regression, as we currently support profiling forked processes.  If this feature is needed, perhaps it should be opt-in.

**Comment by cmcantalupo** [comment]
Will not fix
