### ISSUE TITLE
LearningBalancer implementation

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#339]

**Comment by alawibaba** [comment]
Broke this down in advance of our planning meeting:

https://github.com/geopm/geopm/issues/401
https://github.com/geopm/geopm/issues/402
https://github.com/geopm/geopm/issues/403
https://github.com/geopm/geopm/issues/404
https://github.com/geopm/geopm/issues/405
https://github.com/geopm/geopm/issues/406
