### ISSUE TITLE
Tutorial 0 application hangs at certain number of  MPI ranks

### ISSUE THREAD

**Issue by amarathe84** [geopm/geopm#34]
Distributed run of tutorial_0 application with 4 MPI ranks finishes but hangs at other MPI rank counts: 

```
$ srun -N 2 -n 4 ./tutorial_0.sh 
MPI_COMM_WORLD size: 2
Sleeping for five seconds
<application finished>
$ srun -N 2 -n 42 ./tutorial_0.sh 
MPI_COMM_WORLD size: 40
Sleeping for five seconds
<application didn't finish>

```

Compiler tool-chain used: gcc 4.9.2, mvapich2-gnu 2.1.

**Comment by sssylvester** [comment]
If you configure with --enable-debug you get the following error:

    Error: <geopm> MPI ranks are not affitinized to distinct CPUs: Profile: set GEOPM_ERROR_AFFINITY_IGNORE to ignore error: at geopm/src/Profile.cpp:307

This is due to MPI/slurm oversubscribing the HW. GEO requires all processes to be pinned to distinct hardware threads. If you add the following to your command-line it should work:

    --auto-affinity=start=0,cpt=1
