### ISSUE TITLE
Epoch energy includes MPI and ignore regions

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#341]
Epoch runtime correctly excludes MPI and ignore regions, but energy is calculated with a simple difference between start and end energy.  To be consistent with the reported runtime, the energy total should exclude MPI and ignore regions.

**Comment by cmcantalupo** [comment]
https://review.gerrithub.io/#/c/geopm/geopm/+/423576/

**Comment by dianarg** [comment]
This is no longer a problem because epoch sync-runtime includes MPI and ignore, so it is consistent with the energy.
