### ISSUE TITLE
As an end-user I would like to be able to use geopmsession on a multi-node run to gather summary statistics

### ISSUE THREAD

**Issue by asmaalrawi** [geopm/geopm#3542]
Relates to #408 

I can't easily use geopmsession to monitor aggregate statistics at scale for multi-node runs. (e.g. if I want to monitor maximum power consumption per-node) in a way that scales well with number of nodes.

A new python class (based on the Session class) reads signals provided by the end user in a file. When the job is launched, mpi is used to read signals per-node and ingest them into a data frame. At the end of the run, statistics are exported in a json or csv file.

Alternatives considered: 

- Per-node files are handled in post-processing and consolidated into a single file. This would be data-intensive and thus would not scale well.
- geopmsession is extended with a new command line option for stats aggregation output rather than trace output
- A new user signal is created for any statistics that are needed
- Use the geopm runtime whenever large-scale aggregate statistics are desired

**Comment by cmcantalupo** [comment]
Remaining work:
https://github.com/geopm/geopm/pull/3543/

- [x] Documentation additions for geopmsession.1.rst
- [x] Add doc strings and doxygen to all public interfaces
- [x] Fix broken unit tests by updating mocks (False as new last argument to run_read())
- [x] Unit test coverage for StatsCollector.cpp
- [x] ~Unit test coverage for report logic in session.py~ Create tech debt issue around missing integration tests for geopmsession CLI: https://github.com/geopm/geopm/issues/2843
- [x] ~Unit test coverage for MPI logic in session.py~
- [x] Provide dates in ISO format with nano-seconds included 
- [x] Create tech debt issue, or provide context for StatsCollector (no singleton)
- [x] Create tech debt issue and put behind beta flag, or provide API the C api as below with adjusted python bindings

The changes to the geopm_stats_collector*() APIs could look something like
```C
int GEOPM_PUBLIC
    geopm_stats_collector_create(size_t num_requests, const struct geopm_request_s *requests,
        struct geopm_stats_collector_s **collector);

int GEOPM_PUBLIC
    geopm_stats_collector_update(struct geopm_stats_collector_s *collector);

// if *max_report_size is zero, update it with the required size for the report and do not modify report 
int GEOPM_PUBLIC
    geopm_stats_collector_report_yaml(const struct geopm_stats_collector_s *collector,
        size_t *report_size, char *report_yaml);

int GEOPM_PUBLIC
    geopm_stats_collector_clear(struct geopm_stats_collector_s *collector);

int GEOPM_PUBLIC
    geopm_stats_collector_free(geopm_stats_collector_s *collector);

```
