### ISSUE TITLE
LevelZero.cpp should check for negative frequency readings from LevelZero

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#3589]
**Describe the bug**
GEOPM occasionally returns negative frequency readings for `LevelZero::GPU_CORE_FREQUENCY_STATUS`.

**Root cause**
[zesFrequencyGetState](https://spec.oneapi.io/level-zero/latest/sysman/api.html#zesfrequencygetstate) may return a negative frequency reading when LevelZero is unable to acquire the actual value.

**Suggested fix**
Check for negative frequency readings in [LevelZeroImp::frequency_status](https://github.com/geopm/geopm/blob/dev/libgeopmd/src/LevelZero.cpp#L784). Return NaN in place of negative frequency readings.

**Comment by asmaalrawi** [comment]
We've also seen this for GPU utilization signals.
