### ISSUE TITLE
Report shows NaN when aggregating signals with NaN rather than skipping those timesteps.

### ISSUE THREAD

**Issue by asmaalrawi** [geopm/geopm#3592]
**Describe the bug**
I tried to generate a report that included average GPU activity. The report output NaN. When running the workload with geopmsession, the trace shows several lines of NaN for GPU_CORE_ACTIVITY while the GPU is inactive. 

On other signals where the first line is NaN, the report outputs the correct aggregation, ignoring the first line.

**GEOPM version**
v3.1.0

**Expected behavior**

Some number between 0 and 1 for GPU_CORE_ACTIVITY@gpu_chip-n

```
    Application Totals:
      GPU_CORE_ACTIVITY@gpu_chip-0: 0.93
      GPU_CORE_ACTIVITY@gpu_chip-1: 0.95
      GPU_CORE_ACTIVITY@gpu_chip-2: 0.99

```
**Actual behavior**

NaNs

```
    Application Totals:
      GPU_CORE_ACTIVITY@gpu_chip-0: nan
      GPU_CORE_ACTIVITY@gpu_chip-1: nan
      GPU_CORE_ACTIVITY@gpu_chip-2: nan

```

**Error messages produced**
N/A

Relates to #3550

**Comment by bgeltz** [comment]
Chris mentioned during standup that this bug is really about a theoretical, non-existent signal that has this behavior.  The PR#3586 will prevent GPU_ACTIVITY from ever producing NAN, so that will close #3550.

**Comment by asmaalrawi** [comment]
> Chris mentioned during standup that this bug is really about a theoretical, non-existent signal that has this behavior. The PR#3586 will prevent GPU_ACTIVITY from ever producing NAN, so that will close #3550.

I'm not sure that this is purely theoretical. GPU power signals use a timestamp collected from HW. Although I tried sampling as rapidly as possible and never saw a NaN, it's not necessarily a given that it will never happen.

This also addresses the behavior change introduced in #3550 which is referenced <a href="https://github.com/geopm/geopm/pull/3586#issuecomment-2350061389">in this comment</a>. Before, any derivative samples where the timestamp is identical to the previous sample would be returned as the previous value. Now, they will be returned as NaN.
