### ISSUE TITLE
msr_data_spr.json has the wrong scaling factor for DRAM_ENERGY_STATUS:ENERGY

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#3651]
**Describe the bug**
I tried to read DRAM power on an SPR system and it was 1/4 of the expected value.

**GEOPM version**
3.1.0

**Expected behavior**
`geopmread DRAM_POWER package 0` should print the DRAM power consumption on CPU 0.

**Actual behavior**
On SPR, `geopmread DRAM_POWER package 0` prints 1/4 the DRAM power consumption on CPU 0.

**Error messages produced**
None

**Additional context**
The current scaling factor for DRAM_ENERGY_STATUS:ENERGY in msr_data_spr.json is `1.5258789063e-05`. It should be the same as the value in PKG_ENERGY_STATUS (`6.103515625e-05`). 

Even better, the MSRIOGroup could read MSR::RAPL_POWER_UNIT:ENERGY to query the scaling factor from the target platform.

**Comment by bgeltz** [comment]
Additional context on how we got into this state:

``1.5258789063e-05`` got into the codebase during the v1.0 release:
https://github.com/geopm/geopm/commit/2e37b3f5fedf5725004e7f82847eac28563e70d2

Comments indicate that the MSR provided data was incorrect for ``MSR::RAPL_POWER_UNIT:ENERGY``: https://github.com/geopm/geopm/pull/497#issuecomment-457769208

The above commit changed the scalar to ``1.5258789063e-05`` for HSX, KNL, SKX, and SNB.  This value persisted through the JSON re-write of all of this data, and was copied into the SPR description file from SKX when it was created for release v3.0: https://github.com/geopm/geopm/commit/1b8e623c53509663e7ceec6e1a475474a58a05ff
