### ISSUE TITLE
Synchronization of ranks in MPI_Finalize is not accounted for in report as MPI time

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#370]
If an application has no synchronization (like geopmbench with dgemm only) then the time imbalance across ranks is considered non-mpi epoch time in the report.

**Comment by bgeltz** [comment]
MPI_Barrier (*not* PMPI) in MPI_Finalize prior to calling shutdown?

**Comment by cmcantalupo** [comment]
https://github.com/geopm/geopm/commit/e57eab5724892a4a85106a17ab06cc2ae04216c8
