### ISSUE TITLE
geopmanalysis and impi's mpiexec

### ISSUE THREAD

**Issue by maiterth** [geopm/geopm#378]
geopmanalysis currently supports slurms srun arguments.
The geopm-rm argument and GEOPM_RM arguments for the usage of impi's mpiexec clash with some options used and added by the analysis script.

The command line options:
-N is not understood by mpiexec, and required by geopmanalysis 
--ppn is needed by mpiexec but not understood by geopmanalysis. (when using impi)

The launch options for geopmanalysis and geopmsrun / geopmaprun with non-default resource managers should be aligned and checked.

**Comment by dianarg** [comment]
Thanks for adding this issue.  Another problem is that we don't have any way to pass options in general forward to the launch command, e.g. -x for slurm/-E for aprun to exclude nodes, GEOPM options such as --geopm-barrier, etc.  It would be much less confusing if the launch part of the analysis had the same interface as our launcher.

**Comment by dianarg** [comment]
One solution would be to implement #253
