### ISSUE TITLE
Add GEOPM Tutorial text about GEOPM/Darshan conflict over PMPI usage

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#397]
Only one set of PMPI wrappers can be in place at any given time.

**Comment by cmcantalupo** [comment]
Adding text to known issues, but this should also be handled with a module conflict:

```
confict("darshan")
```

in the geopm module file.

**Comment by cmcantalupo** [comment]
conflict "darshan" has been added to the theta module for geopm and theta QUICKSTART.md has been updated to reflect this change.
