### ISSUE TITLE
Fix OBS builds for standard distro packaging

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#419]
Builds on opensuse.build.org have been failing since 0.5.1+dev31g09e482d, i.e. 09e482d.

**Comment by cmcantalupo** [comment]
Builds are working, auto push from Travis is not.

**Comment by dannosliwcd** [comment]
`./copying_headers/test-dist` moves `geopm-$version.tar.gz`, and `.travis_obs.sh` later expects that file to be present
