### ISSUE TITLE
Automation of OBS builds failing

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#42]
Travis is giving error 500 when curl is used to upload the tarball and spec file to OBS.  This prevents automation from triggering builds in OBS.

**Comment by bgeltz** [comment]
This was fixed with commits https://github.com/geopm/geopm/commit/74f857144b716ec536074831a60d2e2640536c91 and https://github.com/geopm/geopm/commit/494965e491dfc722abc773db2cc9ae948e50386d.
