### ISSUE TITLE
Add man page for each installed C++ header with hyperlink

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#423]
For all installed C++ headers which do not have a hand written man page, install a man page for each class which links to the published doxygen web page, e.g.

https://geopm.github.io/dox/classgeopm_1_1_exception.html

A brief SYNOPSIS and DESCRIPTION section might be nice as well.

**Comment by dianarg** [comment]
b0f909c893480bd2bb060cb48514525cf04e6cc6
