### ISSUE TITLE
geopmpolicy fails on examples from man page

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#44]
The geopmpolicy application is failing to create basic json configuration files.  One example is below.  The version of geopm is 0.1.1+dev258g6f85d33 from SHA 6f85d33.

    geopmpolicy -c -f geopm.conf -m perf_balance_dynamic -d 'power_budget:145'
    Error: <geopm> Invalid argument: GlobalPolicy::check_valid(): dynamic mode does not match the required decider: at geopm/src/GlobalPolicy.cpp:732
    Error: <geopm> Invalid argument.

**Comment by cmcantalupo** [comment]
Steve is working on the fix for this here:

https://review.gerrithub.io/#/c/296120/

**Comment by sssylvester** [comment]
This is fixed as of 2676d9b39f55ebeba946180e184ac7f47daf9ae7
