### ISSUE TITLE
Pass number of ranks/nodes to analysis launch() for testing

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#444]
Instead of having the energy efficient test call num_rank_option() and num_node_option() on a temporary launcher, have the test pass these values through to the analysis.launch() call, which creates a launcher.

**Comment by dianarg** [comment]
The launcher being passed to Analysis constructor could also move to parameters of launch()

**Comment by bakerbrandond** [comment]
analysis no longer needed for testing
