### ISSUE TITLE
geopmsrun and geomaprun not being created with initial installation

### ISSUE THREAD

**Issue by tspelce** [geopm/geopm#456]

**Comment by tspelce** [comment]
I had a need to reinstall geopm ... I installed it on the same machine as previously done using the same procedure (autogen.sh, ./configure , make, make install ) and everything appears to work as expected except that geopmsrun and geopmaprun are not created. Has anyone observed this ? I'm building using Intel compilers, etc.

**Comment by bakerbrandond** [comment]
The binaries have been combined and the required interaction has changed and is documented [here](https://github.com/geopm/geopm/blob/dev/ronn/geopmlaunch.1.ronn#examples).  Still to be merged to public web page, apologies.
