### ISSUE TITLE
Inconsistent error checking in TimeIOGroup and CpuinfoIOGroup

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#493]
The domain of the TIME signal is M_DOMAIN_BOARD, but no error is thrown if this signal is pushed or read for another domain.

**Comment by bakerbrandond** [comment]
I believe this is by design as the concept of time doesn't change with domain. Is there such use case?

**Comment by bakerbrandond** [comment]
And as I hit send I thought of a possible one... Say time source from an accelerator card?

**Comment by dianarg** [comment]
It's inconsistent with how the other IOGroups work because we can only return one domain from signal_domain_type().  Normally, if you call push_signal on the IOGroup with anything other than the return from signal_domain_type, it throws an error.  We just need to clarify what the expected behavior is.

**Comment by dianarg** [comment]
There is a similar inconsistency in CpuinfoIOGroup.  push_signal() throws if the domain is not M_DOMAIN_BOARD, but read_signal() accepts board, package, core, and cpu.

**Comment by dianarg** [comment]
I think in the process of fixing up TimeIOGroup, it makes sense to change the domain of the TIME signal to M_DOMAIN_CPU so that it can be aggregated to other domains in the report/trace.  See #483.
