### ISSUE TITLE
Warning about missing MSRs

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#498]
> estimate 1

During MSRIOGroup's save and restore control step, reading/writing MSRs is best effort.  Even when MSRs fail and are skipped, the warning message that shows up looks like an error:
```<geopm> Could not write to MSR device: MSRIO::write_msr(): pwrite() failed at offset 0x19c system error: Permission denied: at geopm/src/MSRIO.cpp:111```

Also, the same message appears for every node, which can be a lot of output.

**Comment by dianarg** [comment]
A nicer solution would be to have the MSRIOGroup examine the whitelist (not possible on every system) and remove controls that are not supported.  They should not show up in the list of controls printed by `geopmwrite`.

**Comment by dianarg** [comment]
Also, in MSRIOImp::read_msr, the exception error code is incorrectly GEOPM_ERROR_MSR_WRITE, which also makes warnings from the save_control step seem like they are trying to write.  The error message appears as: ```<geopm> Could not write to MSR device: MSRIOImp::read_msr(): pread() failed at offset 0x620 system error: Permission denied: at geopm/src/MSRIO.cpp:98```

This has been fixed.

**Comment by cmcantalupo** [comment]
TODO: Confirm that this is no longer an issue and can be closed.
