### ISSUE TITLE
GEOPM articles for website

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#518]
Add a list of articles and papers mentioning GEOPM to the website

**Comment by sidjana** [comment]
Might also make sense to add an extra section that points to GEOPM-related slides presented in open forums. Also, perhaps an “Events” section for all list of all the upcoming talks/presentations/webinars/BoFs/ tutorials in public venues.

**Comment by cmcantalupo** [comment]
Updates should go here:

https://geopm.github.io/publications.html
