### ISSUE TITLE
Do not allow nesting of MPI regions within network hint regions.

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#533]
Work in progress here:

https://review.gerrithub.io/c/geopm/geopm/+/445982

Please change author if work gets completed :)

**Comment by bgeltz** [comment]
I ended up cherry-picking that patch onto the branch I've been testing on Theta (bgeltz-shmem):
bgeltz/geopm@8d5708a01bf9c394c067ad6d3f0174f6816755cd

After studying it for a while, I ended up not making any changes to the patch.  I couldn't see why other changes would be necessary.

I tested it on Mr. Fusion by first identifying one of the regions within HACC's hot loop that had a significant chunk of time in MPI.  This ended up being the "ignore2" region based on the current markup I'm testing.  By marking that region with the network hint, and doing 2 runs (without and with the above patch), I was able to verify that the MPI time for this region disappears with the patch.  

That's expected AFAICT: GEOPM is no longer aware of MPI calls occurring within this region and thus won't have any data to report on.  A visual spot check of the other regions makes it appear to function as expected.  I didn't see any discrepancies in the other regions comparing the before and after datasets.

I've just now queued jobs on Theta from the tip of this branch (configured WITHOUT tracing), so hopefully I'll have something to report out on Monday.
