### ISSUE TITLE
Rework Agent policy and sample handling

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#548]
- Need to come to agreement about behavior
- Name of method
- Update documentation

**Comment by cmcantalupo** [comment]
Requires modifications to Agent unit tests.

**Comment by dianarg** [comment]
1. leave controller as is, implement ascend/descend in base class (virtual)
    - also add new methods as virtual with empty implementation
    - See: https://review.gerrithub.io/c/geopm/geopm/+/449497
2. have each agent implement new APIs in parallel
3. require new apis (make pure virtual), remove ascend/descend base class implementation
     - renaming in each agent
