### ISSUE TITLE
PERF_CTL and PERF_STATUS set as package scoped for all platforms

### ISSUE THREAD

**Issue by lhlawson** [geopm/geopm#568]
With the change to JSON strings for MSRIOGroup (commit ba2a071814871c78b67eebdf563ba307ce735d7c) PERF_CTL was moved to the msr_data_arch.cpp file and give the package level scope.  This effectively sets the frequency knob to package scoped for all architectures.

Previous implementation (shown here: https://github.com/geopm/geopm/commit/1e659437f8665364df7dc76c64da8aac3b900afd) correctly had PERF_STATUS as cpu domain and PERF_CTL as core domain for SKX and HSX.  KNL previously had a PERF_STATUS as package so no change is needed there.  

Related issue indicating that core and cpu domain scoping worked on SKX (closed in 2018): https://github.com/geopm/geopm/issues/249

**Comment by dianarg** [comment]
https://github.com/geopm/geopm/commit/2d3a19487167254d756e61df37601dfda0226e1b
