### ISSUE TITLE
Provide runtime switch to use procfs or sched_getaffinity()

### ISSUE THREAD

**Issue by sbtrasi** [geopm/geopm#581]
mOS has Linux and LWK partition on a node. When running apps on LWK we won't be able use /proc/self/status to determine the affinity mask of the rank. But in a different situation when running app on Linux partition of mOS we could use procfs instead of sched_getaffinity().

Currently the solution is to use a different build of GeoPM on mOS which uses '--disable-procfs'. But I wonder if a dynamic switch is more useful with a default behavior set to use sched_getaffinity ?

**Comment by cmcantalupo** [comment]
procfs option is no longer supported.
