### ISSUE TITLE
Set GEOPM_TIMEOUT to 0 if not launching geopm

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#597]
If a user links their application with libgeopm but runs the application without geopm, they will still get a 30 second timeout waiting for the controller.  This should be set up so that there is no wait when running without geopm, and increase the timeout to the default 30s when using the launcher or when GEOPM_CTL/GEOPM_REPORT/GEOPM_PROFILE are set.

**Comment by dianarg** [comment]
Related to #499

**Comment by sidjana** [comment]
Set the TIMEOUT to 0 by default. Have the launching script be responsible for setting to a different value when GEOPM is used.

**Comment by bgeltz** [comment]
The implementation around this has changed.  The application no longer waits on the specified GEOPM_TIMEOUT.  Only the controller will wait if it is set.
