### ISSUE TITLE
Use agg:sum for geopmread POWER_PACKAGE_TDP board

### ISSUE THREAD

**Issue by bgeltz** [geopm/geopm#599]
Currently issuing geopmread for the TDP signal for the board domain returns the value for a single socket.  On a multi socket system, requesting this at the board domain should sum the value for all sockets.

This will aid in policy construction for power balancer, etc. as they require limits set for the entire board.

**Comment by bgeltz** [comment]
Think about `POWER_PACKAGE_TDP` vs. `POWER_TDP` as a PlatformIO alias to solve this.  It's not avoidable for low-level implementations, but should work for higher level aliases.

**Comment by dianarg** [comment]
If sum() is appropriate for the aggregation function for POWER_PACKAGE_TDP, it makes sense to change POWER_PACKAGE_MIN and POWER_PACKAGE_MAX also.
