### ISSUE TITLE
Update PlatformTopo C++ man page

### ISSUE THREAD

**Issue by vysocky** [geopm/geopm#605]
[Man page of PlatformTopo](https://geopm.github.io/man/GEOPM_CXX_MAN_PlatformTopo.3.html) refers to `geopm::PlatformTopo::domain_cpus(...)`, which is not a method of the class any more.

```
using geopm::PlatformTopo;

int main() {
    PlatformTopo &topo = geopm::platform_topo();
...
    for (int pkg_idx = 0; pkg_idx < num_pkgs; ++pkg_idx) {
        std::cout << "CPUs on package " << pkg_idx << ": ";
        std::set<int> cpus = topo.domain_cpus(GEOPM_DOMAIN_PACKAGE, pkg_idx);
        for(auto pcpu : cpus) {
            std::cout << pcpu << " ";
        }
        std::cout << std::endl;
    }
```
Also geopm::platform_topo() return type is now  `const`.

#454

**Comment by cmcantalupo** [comment]
Thank for the feedback @vysocky!  The domain_cpus() became private and was replaced by the more general domain_nested() method.  I will update the documentation to reflect this change soon.

**Comment by cmcantalupo** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/455130
