### ISSUE TITLE
Option to produce YAML-formatted reports

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#615]
If report name ends in .yml or .yaml, write in YAML format instead of legacy format.
For acceptance, this change should also either a) use a relatively stable YAML library to produce standard YAML, or b) add an integration test that checks that produced report files are correct YAML.

**Comment by cmcantalupo** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/471781

**Comment by cmcantalupo** [comment]
Reports are now always YAML formatted, issue #954 and #1483 notwithstanding.
