### ISSUE TITLE
Example and test binaries not completely built

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#627]
The programs that are not installed (e.g. nas_ft) cannot be run on the compute nodes of mcfly after compiling.  They need to be run once on the head node, at which point the .libs folder is created, then they work on compute nodes.   This is also a problem for test_integration/test_ee_stream_dgemm_mix from this patch: https://review.gerrithub.io/c/geopm/geopm/+/456392

**Comment by bgeltz** [comment]
I just checked this after a fresh build.  In examining ```<src_root>/integration/apps/nasft/nasft```, I see a ```nas_ft``` binary in that directory, and a corresponding one in the ```.libs``` subdirectory.  This must have been resolved when all the example apps were refactored into ```integration/apps```.
