### ISSUE TITLE
Launcher does not support more OMP threads per core than hyperthreads

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#631]
Given a launch command with OMP_NUM_THREADS set such as:
```OMP_NUM_THREADS=4 geopmlaunch srun -N 1 -n 42 -- geopmbench```
the launcher will try to assign cores to ranks assuming 1 OMP thread per hyperthread (mcfly has 44 cores and 2 hyperthreads).  It fails with the message: ```<geopmpy.launcher> Cores cannot be shared between MPI ranks```

**Comment by sidjana** [comment]
Improve the error message to reflect the OMP misconfig.
