### ISSUE TITLE
Keep track of most up to date benchmark source

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#659]

**Comment by bgeltz** [comment]
I've repurposed the master branch of the apps repo (TeamForge) for this purpose.  I've currently integrated HACC and Nekbone, along with any supporting tools and run scripts that I've used in the past.

The only open right now is MiniFE.

**Comment by bgeltz** [comment]
Closing.  I added HACC for Xeon, and am holding off on MiniFE until we need it again.  The code in examples/minife will suffice for now.
