### ISSUE TITLE
Update the geopmpy.io to support new trace format header

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#696]
Header format is changed by this patch: https://review.gerrithub.io/c/geopm/geopm/+/464027

Consider providing a tool for converting traces from the previous version to the new version, or support old format in io.py.

**Comment by bgeltz** [comment]
Working off of:
chris-public/cmcantalupo-profile-tracer-rebase5

**Comment by bgeltz** [comment]
rebase6 now

**Comment by dianarg** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/465824
