### ISSUE TITLE
Figure out how to display dynamic policy in the report

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#708]
This may be a large volume of data if the policy was changed frequently.  On the other hand, there may only be one policy for an entire run.

**Comment by bakerbrandond** [comment]
I made my last comment assuming that the information would be added to the report somehow.  Your new trace that we discussed briefly this morning makes much more sense.

**Comment by dianarg** [comment]
WW45: Under review here: 
https://review.gerrithub.io/c/geopm/geopm/+/466960
https://review.gerrithub.io/c/geopm/geopm/+/466961
