### ISSUE TITLE
Silence warning about failed IOGroup load unless PlatformIO::push_signal() etc. throws

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#733]
The warning in the PlatformIO constructor that registers all built-in IOGroups does not provide any useful information unless one of the PlatformIO methods fails due to an unknown signal or control name, e.g. push_signal(), read_signal(), push_control(), etc.

After completing this feature, the configure flag for enable-cnl-iogroup can be removed.

**Comment by cmcantalupo** [comment]
These warnings are currently hidden without enabling debug.  I'm not sure delaying these debug only warnings is helpful.
