### ISSUE TITLE
low-frequency-mpi

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#76]
Investigate the impact of lowering power limit inside of MPI regions which are expected to be long running.  For example lower power for MPI_Send if payload is larger than some minimum, but do not lower power for MPI_ISend or other non-blocking calls.  This could improve energy efficiency.

**Comment by dianarg** [comment]
This is already a feature of the EE agent; still need this issue?

**Comment by maiterth** [comment]
I think with the EE agent and Countdown this is good.
