### ISSUE TITLE
GEOPM plugin python wrappers only able to access builtin agents

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#764]
Though geopmagent CLI is able to access plugin agents as specified by GEOPM_PLUGIN_PATH the python wrappers are not able to:
CLI:
```
$ geopmagent
monitor
power_balancer
power_governor
energy_efficient
frequency_map
example
```

Python:
```
>>> import os
>>> print(os.environ['GEOPM_PLUGIN_PATH'])
/home/bbaker1/dev/geopm/tutorial/agent
>>> num_agent = _ffi.new("int *")
>>> err = _dl.geopm_agent_num_avail(num_agent)
>>> err
0
>>> num_agent[0]
5
```

**Comment by bakerbrandond** [comment]
create an integration test that adds the example plugins the plugin path and verifies the Python C-wrappers are able to list and describe the plugins.  Dependent on #396 which is tracking the fact that none of the test infrastructure currently builds the tutorials.

**Comment by dannosliwcd** [comment]
https://review.gerrithub.io/c/geopm/geopm/+/475803 has a proposed solution. Alternatively, it would be nice if we could be explicit about load order.

**Comment by dianarg** [comment]
Related to #986
