### ISSUE TITLE
Configurable permissions for SharedMemory

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#768]
To support the Endpoint, SharedMemory needs to support being created with world-writable permissions (for the sample endpoint shmem) or owner-only write permissions (for the policy endpoint shmem).  Currently the permissions are hardcoded in the SharedMemoryImp constructor.

**Comment by cmcantalupo** [comment]
https://github.com/geopm/geopm/blob/dev/service/src/geopm/SharedMemory.hpp#L73-L80
