### ISSUE TITLE
Add Region IDs to geopm reports

### ISSUE THREAD

**Issue by sssylvester** [geopm/geopm#78]
Add region ids to the report so that they can be used to help parse trace files or debug.

Example:
##### geopm 0.2.0 #####

Profile: /home/sssylves/repos/geopm/test_integration/.libs/geopm_test_integration
Region sleep (1399617935):
	runtime (sec): 1.00101
	energy (joules): 100.676
	frequency (%): 107.692
	count: 1
Region model-init (1682937735):
	runtime (sec): 0.00164156
	energy (joules): 0.0948792
	frequency (%): 107.858
	count: 1
Region epoch (9223372036854775808):
	runtime (sec): 0
	energy (joules): 0
	frequency (%): 0
	count: 1
Application Totals:
	runtime (sec): 1.62989
	energy (joules): 162.085
	mpi-runtime (sec): 0

**Comment by cmcantalupo** [comment]
Fixed by 793c173
