### ISSUE TITLE
Code freeze for v1.1.0 release

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#796]
List of all gerrithub patches required for release:

- [x] https://review.gerrithub.io/c/geopm/geopm/+/473244
- [x] https://review.gerrithub.io/c/geopm/geopm/+/471409
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473347
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473352
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473353
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473358
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473357
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473363
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473364
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473572
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473577
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473579
- [x] https://review.gerrithub.io/c/geopm/geopm/+/473589

**Comment by bgeltz** [comment]
Diana's - https://review.gerrithub.io/c/geopm/geopm/+/473357
https://review.gerrithub.io/c/geopm/geopm/+/471409
