### ISSUE TITLE
As a system administrator, I would like to have a user manual that describes how to integrate GEOPM with the resource manager on my system.

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#806]
Use Case
----------

As a system administrator with an existing cluster running in production, I will read the user guide and understand how to configure my cluster support using GEOPM to provide a system wide capability.

Done Criterion
---------------

A user guide or man page exists that explains how to implement several specific system wide energy and power goals that can be enforced using GEOPM.

Notes
------

Current documentation for these features can be found in the "Resource Manager Integration" section of the README, man pages for individual interfaces (e.g. geopm_endpoint_c(3) and geopm_policystore_c(3) ), and in the README for the github.com/geopm/geopm-slurm repo.

It would be nice to have a more unified source of information.  I can think of a few possibilities:
- expand existing section in the README into a guide for system admins wanting to enable this integration.  In particular, this section is missing information about how to use the endpoint interface.  See #805
- a tutorial for sysadmins similar to the integration tests showing how to use the environment overrides, static policy, policystore, and endpoint.  This could have its own README.
- some kind of guide or tutorial for users who will run on these systems, basically explaining why they shouldn't try to set their own policies, and how the profile might be used.  I can see this sort of guide being customized for each site.

This issue is complicated by the fact that the slurm plugins currently live in the other repo (geopm-slurm).  Related to #779

**Comment by bgeltz** [comment]
#912 and #913 are future work added at the end of sprint milestone 55.
