### ISSUE TITLE
Integration tests clean up output files even on failure

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#817]
If GEOPM_KEEP_FILES is not set, files will be cleaned up regardless of the test outcome.  This is because `sys.exc_info() == (None, None, None)` is always true in the tearDown context in Python3.  See https://stackoverflow.com/questions/4414234/getting-pythons-unittest-results-in-a-teardown-method#comment78911300_4414788

A workaround is to always set GEOPM_KEEP_FILES and manually remove the test output files if not needed.

**Comment by bgeltz** [comment]
Add'fl info about using sys.exc_clear():
https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/

**Comment by cmcantalupo** [comment]
If we change the default we need to update the documentation here:

https://github.com/geopm/geopm/tree/dev/test_integration#geopm_keep_files

**Comment by cmcantalupo** [comment]
The proposal is to always keep files, and have the nightly script take on the responsibility of cleaning up after itself, thus removing the feature requirement from integration tests.
