### ISSUE TITLE
There is no way to perform multiple power measurements.

### ISSUE THREAD

**Issue by tigrux** [geopm/geopm#827]
The singleton geopm::platform_io, once a push_signal is performed, never resets the flag m_is_active to false. A work around is to instantiate a non-public class:

const auto platform_io = std::make_unique<geopm::PlatformIOImp>();
const auto idx = platform_io->push_signal(signal_name, domain_type, domain_index);
[...]

This code is used in a daemon started by systemd, that reads on-demand, i.e. not in a cli tool.

**Comment by dianarg** [comment]
Thanks for opening the issue @tigrux .  The solution for this will be to fix PlatformIO::read_signal() to support power measurements.
