### ISSUE TITLE
MPI_Gather and geopm

### ISSUE THREAD

**Issue by slabasan** [geopm/geopm#83]
I'm running into troubles doing a simple MPI_Gather of rank IDs when using geopm's profiling feature. The number of ranks is correct, but the results are garbage values. I'm running my example with 4 nodes and 8 tasks, 2 tasks per node. With geopm, I would expect the rank IDs to be 0 and 1. 

I've put a reproducer code here: 
git clone https://github.com/slabasan/mpigather-geopm.git

Let me know if you have any questions. Thank you!

**Comment by cmcantalupo** [comment]
Thanks for finding this bug and for the nice reproducer!  I think the fix is here:

https://github.com/cmcantalupo/geopm/tree/cmcantalupo-fix-gather-wrapper

Let me  know if that works for you.  We had forgotten to swap the communicator for the MPI_Gather() and MPI_Gatherv() wrapper routines.

**Comment by slabasan** [comment]
@cmcantalupo Thank you! Problem fixed!
