### ISSUE TITLE
System configuration checker

### ISSUE THREAD

**Issue by dannosliwcd** [geopm/geopm#847]
It would be nice to have a script that checks for GEOPM compatibility issues on a system. Such a tool could be used to expedite evaluation of a system's configuration when initially setting up GEOPM, 

Examples of things to check:
- Environment variables
- Policy files, if referenced in /etc/geopm
- Ability to access MSRs
- If using SLURM, is the geopm plugin in the plugstack?

**Comment by bgeltz** [comment]
Addressed with #908, the addition of `geopmadmin` and tests in #888.
