### ISSUE TITLE
Implement command line option to geopmlaunch to disable OMPT at runtime

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#860]
> estimate 2

Task
----

Add python code to parse `--geopm-ompt-disable` and add `GEOPM_OMPT_DISABLE` to Environment class management.  The done criterion for this issue does not include using this feature.  

Done Criterion
--------------

- New API to Environment::do_ompt()
- TestEnvironment modified to call API and check that it reflects the environment settings
- Implement python to support setting environment variable based on command line option

Parent story #854

**Comment by dannosliwcd** [comment]
Reordered the words in the option and the environment variable based on a discussion from yesterday. Existing options follow the updated word order.
