### ISSUE TITLE
Modify the energy efficient agent so that it changes frequency upon region entry and reduces controller wait if hardware supports fast p-state transitions

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#865]
> estimate 3

Energy efficient agent should check if the hardware can support fast p-state transitions.  If it can, the control loop should be reduced to 2 ms and the number of samples required to transition frequency should be reduced to zero.  
SEE COMMENTS BELOW

Requires: #864 

Parent story: #855

**Comment by bgeltz** [comment]
The scope of this issue changed a bit such that the 2ms control gate and not requiring adjacent samples for network and unmarked is the default, and there's no case for why we should preserve the legacy behavior.

As such PR #899 makes this the default, and this issue should be closed when the PR is merged.
