### ISSUE TITLE
As a system administrator, I want to verify that the GEOPM environment files are set up correctly and are used for all GEOPM jobs

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#875]
> estimate 5

### Use Case
If a system is set up with environment override for the agent and/or policy, all GEOPM jobs should use that agent and policy.  System administrators need instructions on how to set up this configuration and a test script to check that the feature is working for jobs

### Done Criteria
- Script that checks that environment values are always used when launching a job with GEOPM, regardless of whether the user provides a different agent and/or policy.  Correct policy should appear in the report.

**Comment by bgeltz** [comment]
Merged with PR #904.
