### ISSUE TITLE
TestIntegration.test_no_report_and_trace_generation does not make any assertions on file presence

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#894]
https://github.com/geopm/geopm/blob/dev/test_integration/geopm_test_integration.py#L169-L181

**Comment by bgeltz** [comment]
@bakerbrandond You need to make those permalinks when you copy them (it's an option in the sidebar I think), otherwise they point to whatever the current state of the code is in dev.  Right now, that link points off into la-la-land.
