### ISSUE TITLE
Agent custom report fields can break report parsing

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#954]
If an agent adds a field to the report with a key of the form: 'Region xx (0x000):', the parser will treat it as one of the regions added by the Reporter and it will be parsed incorrectly.

**Comment by cmcantalupo** [comment]
Documentation is missing from the Agent man page, and with this documentation, we may be able to close the bug.  An alternative is to add a feature to the controller that throws when a field like this is provided by the Agent.  The best solution yet is to rearrange the report into a more hierarchical form with yaml.  Related to #615.
