### ISSUE TITLE
Make geopmread -d more useful for python caller

### ISSUE THREAD

**Issue by bakerbrandond** [geopm/geopm#964]
Currently geopread -d outputs a human readable table:
```
[bbaker1@mcfly14 geopm](task-946)$ geopmread -d
board                   1
package                 2
core                    44
cpu                     88
board_memory            2
package_memory          0
board_nic               0
package_nic             0
board_accelerator       0
package_accelerator     0
```
One could imagine a usage and output like:
```
[bbaker1@mcfly14 geopm](task-946)$ geopmread -d board
1
```
As geopmread is currently implemented the user will see:
```
[bbaker1@mcfly14 geopm](task-946)$ geopmread -d board
Error: unable to determine signal type: <geopm> Invalid argument: PlatformIOImp::signal_domain_type(): signal name "board" not found: at geopm/src/PlatformIO.cpp:191
```

**Comment by dianarg** [comment]
Unfortunately this has no way to distinguish between a domain type and a signal name.  Maybe a new option like -D?  Alternatively, a python caller can use the interface in geopmpy.topo, rather than launching a binary.  

What is the use case for needing to see the numerical value of the C enum in python code?

**Comment by bakerbrandond** [comment]
I'm not sure I understand the limitation you're describing above.  Please note that it is not the enum value I'm asking for, it is the number of the specified domain.  I guess we could geopmlaunch + geopmpy.topo.  See [here](https://github.com/geopm/geopm/blob/dev/test_integration/geopm_test_integration.py#L105) and imagine a use case like:
```
self._num_cpu = geopm_test_launcher.geopmread("-d cpu")
```
