### ISSUE TITLE
Lead discussion with GADGET developers

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#969]
> estimate 1

Talk to GADGET developers and learn how to run the application at scale.

Done criterion: 
- Participate in meeting.
- After meeting, questions about how to run GADGET have been answered

**Comment by bgeltz** [comment]
The meeting went well, and all of my current ?'s were answered.  There will be a forthcoming email about a dataset I can use at a relatively large scale to enable our current goals.
